// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/config.dart';
import 'api/credential.dart';
import 'api/init.dart';
import 'api/keys.dart';
import 'api/message.dart';
import 'api/storage.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_MlsCredentialPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredentialPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_MlsSignatureKeyPairPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPairPtr;

  @protected
  MlsCredential
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    dynamic raw,
  );

  @protected
  MlsSignatureKeyPair
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    dynamic raw,
  );

  @protected
  MlsCredential
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    dynamic raw,
  );

  @protected
  MlsSignatureKeyPair
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    dynamic raw,
  );

  @protected
  MlsCredential
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    dynamic raw,
  );

  @protected
  MlsSignatureKeyPair
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AddMembersWithStorageResult dco_decode_add_members_with_storage_result(
    dynamic raw,
  );

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  MlsGroupConfig dco_decode_box_autoadd_mls_group_config(dynamic raw);

  @protected
  MlsProposalType dco_decode_box_autoadd_mls_proposal_type(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  CreateGroupWithStorageResult dco_decode_create_group_with_storage_result(
    dynamic raw,
  );

  @protected
  CreateKeyPackageWithStorageResult
  dco_decode_create_key_package_with_storage_result(dynamic raw);

  @protected
  CreateMessageWithStorageResult dco_decode_create_message_with_storage_result(
    dynamic raw,
  );

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  JoinGroupWithStorageResult dco_decode_join_group_with_storage_result(
    dynamic raw,
  );

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

  @protected
  List<MlsCiphersuite> dco_decode_list_mls_ciphersuite(dynamic raw);

  @protected
  List<MlsStorageEntry> dco_decode_list_mls_storage_entry(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MlsCiphersuite dco_decode_mls_ciphersuite(dynamic raw);

  @protected
  MlsGroupConfig dco_decode_mls_group_config(dynamic raw);

  @protected
  MlsProposalType dco_decode_mls_proposal_type(dynamic raw);

  @protected
  MlsStorageBatch dco_decode_mls_storage_batch(dynamic raw);

  @protected
  MlsStorageEntry dco_decode_mls_storage_entry(dynamic raw);

  @protected
  MlsWireFormatPolicy dco_decode_mls_wire_format_policy(dynamic raw);

  @protected
  MlsProposalType? dco_decode_opt_box_autoadd_mls_proposal_type(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  ProcessMessageWithStorageResult
  dco_decode_process_message_with_storage_result(dynamic raw);

  @protected
  ProcessedMessageType dco_decode_processed_message_type(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  MlsCredential
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    SseDeserializer deserializer,
  );

  @protected
  MlsSignatureKeyPair
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    SseDeserializer deserializer,
  );

  @protected
  MlsCredential
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    SseDeserializer deserializer,
  );

  @protected
  MlsSignatureKeyPair
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    SseDeserializer deserializer,
  );

  @protected
  MlsCredential
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    SseDeserializer deserializer,
  );

  @protected
  MlsSignatureKeyPair
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AddMembersWithStorageResult sse_decode_add_members_with_storage_result(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  MlsGroupConfig sse_decode_box_autoadd_mls_group_config(
    SseDeserializer deserializer,
  );

  @protected
  MlsProposalType sse_decode_box_autoadd_mls_proposal_type(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  CreateGroupWithStorageResult sse_decode_create_group_with_storage_result(
    SseDeserializer deserializer,
  );

  @protected
  CreateKeyPackageWithStorageResult
  sse_decode_create_key_package_with_storage_result(
    SseDeserializer deserializer,
  );

  @protected
  CreateMessageWithStorageResult sse_decode_create_message_with_storage_result(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  JoinGroupWithStorageResult sse_decode_join_group_with_storage_result(
    SseDeserializer deserializer,
  );

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  );

  @protected
  List<MlsCiphersuite> sse_decode_list_mls_ciphersuite(
    SseDeserializer deserializer,
  );

  @protected
  List<MlsStorageEntry> sse_decode_list_mls_storage_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MlsCiphersuite sse_decode_mls_ciphersuite(SseDeserializer deserializer);

  @protected
  MlsGroupConfig sse_decode_mls_group_config(SseDeserializer deserializer);

  @protected
  MlsProposalType sse_decode_mls_proposal_type(SseDeserializer deserializer);

  @protected
  MlsStorageBatch sse_decode_mls_storage_batch(SseDeserializer deserializer);

  @protected
  MlsStorageEntry sse_decode_mls_storage_entry(SseDeserializer deserializer);

  @protected
  MlsWireFormatPolicy sse_decode_mls_wire_format_policy(
    SseDeserializer deserializer,
  );

  @protected
  MlsProposalType? sse_decode_opt_box_autoadd_mls_proposal_type(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  ProcessMessageWithStorageResult
  sse_decode_process_message_with_storage_result(SseDeserializer deserializer);

  @protected
  ProcessedMessageType sse_decode_processed_message_type(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<wire_cst_mls_group_config>
  cst_encode_box_autoadd_mls_group_config(MlsGroupConfig raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_mls_group_config();
    cst_api_fill_to_wire_mls_group_config(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<ffi.Int32> cst_encode_box_autoadd_mls_proposal_type(
    MlsProposalType raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_mls_proposal_type(
      cst_encode_mls_proposal_type(raw),
    );
  }

  @protected
  ffi.Pointer<ffi.Uint32> cst_encode_box_autoadd_u_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_u_32(cst_encode_u_32(raw));
  }

  @protected
  ffi.Pointer<wire_cst_list_list_prim_u_8_strict>
  cst_encode_list_list_prim_u_8_strict(List<Uint8List> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_list_prim_u_8_strict(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      ans.ref.ptr[i] = cst_encode_list_prim_u_8_strict(raw[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_mls_ciphersuite> cst_encode_list_mls_ciphersuite(
    List<MlsCiphersuite> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_mls_ciphersuite(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      ans.ref.ptr[i] = cst_encode_mls_ciphersuite(raw[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_mls_storage_entry>
  cst_encode_list_mls_storage_entry(List<MlsStorageEntry> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_mls_storage_entry(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_mls_storage_entry(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_loose> cst_encode_list_prim_u_8_loose(
    List<int> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_loose(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(
    Uint8List raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<ffi.Int32> cst_encode_opt_box_autoadd_mls_proposal_type(
    MlsProposalType? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null
        ? ffi.nullptr
        : cst_encode_box_autoadd_mls_proposal_type(raw);
  }

  @protected
  ffi.Pointer<ffi.Uint32> cst_encode_opt_box_autoadd_u_32(int? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_u_32(raw);
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict>
  cst_encode_opt_list_prim_u_8_strict(Uint8List? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_list_prim_u_8_strict(raw);
  }

  @protected
  int cst_encode_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toSigned(64).toInt();
  }

  @protected
  int cst_encode_usize(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toSigned(64).toInt();
  }

  @protected
  void cst_api_fill_to_wire_add_members_with_storage_result(
    AddMembersWithStorageResult apiObj,
    wire_cst_add_members_with_storage_result wireObj,
  ) {
    wireObj.commit = cst_encode_list_prim_u_8_strict(apiObj.commit);
    wireObj.welcome = cst_encode_list_prim_u_8_strict(apiObj.welcome);
    wireObj.group_info = cst_encode_opt_list_prim_u_8_strict(apiObj.groupInfo);
    cst_api_fill_to_wire_mls_storage_batch(
      apiObj.storageBatch,
      wireObj.storage_batch,
    );
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_mls_group_config(
    MlsGroupConfig apiObj,
    ffi.Pointer<wire_cst_mls_group_config> wireObj,
  ) {
    cst_api_fill_to_wire_mls_group_config(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_create_group_with_storage_result(
    CreateGroupWithStorageResult apiObj,
    wire_cst_create_group_with_storage_result wireObj,
  ) {
    wireObj.group_id = cst_encode_list_prim_u_8_strict(apiObj.groupId);
    cst_api_fill_to_wire_mls_storage_batch(
      apiObj.storageBatch,
      wireObj.storage_batch,
    );
  }

  @protected
  void cst_api_fill_to_wire_create_key_package_with_storage_result(
    CreateKeyPackageWithStorageResult apiObj,
    wire_cst_create_key_package_with_storage_result wireObj,
  ) {
    wireObj.key_package_bytes = cst_encode_list_prim_u_8_strict(
      apiObj.keyPackageBytes,
    );
    cst_api_fill_to_wire_mls_storage_batch(
      apiObj.storageBatch,
      wireObj.storage_batch,
    );
  }

  @protected
  void cst_api_fill_to_wire_create_message_with_storage_result(
    CreateMessageWithStorageResult apiObj,
    wire_cst_create_message_with_storage_result wireObj,
  ) {
    wireObj.ciphertext = cst_encode_list_prim_u_8_strict(apiObj.ciphertext);
    cst_api_fill_to_wire_mls_storage_batch(
      apiObj.storageBatch,
      wireObj.storage_batch,
    );
  }

  @protected
  void cst_api_fill_to_wire_join_group_with_storage_result(
    JoinGroupWithStorageResult apiObj,
    wire_cst_join_group_with_storage_result wireObj,
  ) {
    wireObj.group_id = cst_encode_list_prim_u_8_strict(apiObj.groupId);
    cst_api_fill_to_wire_mls_storage_batch(
      apiObj.storageBatch,
      wireObj.storage_batch,
    );
  }

  @protected
  void cst_api_fill_to_wire_mls_group_config(
    MlsGroupConfig apiObj,
    wire_cst_mls_group_config wireObj,
  ) {
    wireObj.ciphersuite = cst_encode_mls_ciphersuite(apiObj.ciphersuite);
    wireObj.wire_format_policy = cst_encode_mls_wire_format_policy(
      apiObj.wireFormatPolicy,
    );
    wireObj.use_ratchet_tree_extension = cst_encode_bool(
      apiObj.useRatchetTreeExtension,
    );
    wireObj.max_past_epochs = cst_encode_u_32(apiObj.maxPastEpochs);
    wireObj.padding_size = cst_encode_u_32(apiObj.paddingSize);
    wireObj.sender_ratchet_max_out_of_order = cst_encode_u_32(
      apiObj.senderRatchetMaxOutOfOrder,
    );
    wireObj.sender_ratchet_max_forward_distance = cst_encode_u_32(
      apiObj.senderRatchetMaxForwardDistance,
    );
    wireObj.number_of_resumption_psks = cst_encode_u_32(
      apiObj.numberOfResumptionPsks,
    );
  }

  @protected
  void cst_api_fill_to_wire_mls_storage_batch(
    MlsStorageBatch apiObj,
    wire_cst_mls_storage_batch wireObj,
  ) {
    wireObj.upserts = cst_encode_list_mls_storage_entry(apiObj.upserts);
    wireObj.deletes = cst_encode_list_list_prim_u_8_strict(apiObj.deletes);
    wireObj.deleted_group_ids = cst_encode_list_list_prim_u_8_strict(
      apiObj.deletedGroupIds,
    );
    wireObj.storage_format_version = cst_encode_u_32(
      apiObj.storageFormatVersion,
    );
  }

  @protected
  void cst_api_fill_to_wire_mls_storage_entry(
    MlsStorageEntry apiObj,
    wire_cst_mls_storage_entry wireObj,
  ) {
    wireObj.key = cst_encode_list_prim_u_8_strict(apiObj.key);
    wireObj.value = cst_encode_list_prim_u_8_strict(apiObj.value);
    wireObj.group_id = cst_encode_opt_list_prim_u_8_strict(apiObj.groupId);
  }

  @protected
  void cst_api_fill_to_wire_process_message_with_storage_result(
    ProcessMessageWithStorageResult apiObj,
    wire_cst_process_message_with_storage_result wireObj,
  ) {
    wireObj.message_type = cst_encode_processed_message_type(
      apiObj.messageType,
    );
    wireObj.sender_index = cst_encode_opt_box_autoadd_u_32(apiObj.senderIndex);
    wireObj.previous_epoch = cst_encode_u_64(apiObj.previousEpoch);
    wireObj.resulting_epoch = cst_encode_u_64(apiObj.resultingEpoch);
    wireObj.application_message = cst_encode_opt_list_prim_u_8_strict(
      apiObj.applicationMessage,
    );
    wireObj.has_staged_commit = cst_encode_bool(apiObj.hasStagedCommit);
    wireObj.has_proposal = cst_encode_bool(apiObj.hasProposal);
    wireObj.proposal_type = cst_encode_opt_box_autoadd_mls_proposal_type(
      apiObj.proposalType,
    );
    cst_api_fill_to_wire_mls_storage_batch(
      apiObj.storageBatch,
      wireObj.storage_batch,
    );
  }

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    MlsCredential raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    MlsSignatureKeyPair raw,
  );

  @protected
  int
  cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    MlsCredential raw,
  );

  @protected
  int
  cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    MlsSignatureKeyPair raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    MlsCredential raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    MlsSignatureKeyPair raw,
  );

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_mls_ciphersuite(MlsCiphersuite raw);

  @protected
  int cst_encode_mls_proposal_type(MlsProposalType raw);

  @protected
  int cst_encode_mls_wire_format_policy(MlsWireFormatPolicy raw);

  @protected
  int cst_encode_processed_message_type(ProcessedMessageType raw);

  @protected
  int cst_encode_u_16(int raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    MlsCredential self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    MlsSignatureKeyPair self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    MlsCredential self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    MlsSignatureKeyPair self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    MlsCredential self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    MlsSignatureKeyPair self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_add_members_with_storage_result(
    AddMembersWithStorageResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_mls_group_config(
    MlsGroupConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_mls_proposal_type(
    MlsProposalType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_create_group_with_storage_result(
    CreateGroupWithStorageResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_create_key_package_with_storage_result(
    CreateKeyPackageWithStorageResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_create_message_with_storage_result(
    CreateMessageWithStorageResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_join_group_with_storage_result(
    JoinGroupWithStorageResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_mls_ciphersuite(
    List<MlsCiphersuite> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_mls_storage_entry(
    List<MlsStorageEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mls_ciphersuite(
    MlsCiphersuite self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mls_group_config(
    MlsGroupConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mls_proposal_type(
    MlsProposalType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mls_storage_batch(
    MlsStorageBatch self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mls_storage_entry(
    MlsStorageEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mls_wire_format_policy(
    MlsWireFormatPolicy self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_mls_proposal_type(
    MlsProposalType? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_process_message_with_storage_result(
    ProcessMessageWithStorageResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_processed_message_type(
    ProcessedMessageType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import

/// generated by flutter_rust_bridge
class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustLibWire.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void store_dart_post_cobject(DartPostCObjectFnType ptr) {
    return _store_dart_post_cobject(ptr);
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
        'store_dart_post_cobject',
      );
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  WireSyncRust2DartDco wire__crate__api__credential__MlsCredential_basic(
    ffi.Pointer<wire_cst_list_prim_u_8_loose> identity,
  ) {
    return _wire__crate__api__credential__MlsCredential_basic(identity);
  }

  late final _wire__crate__api__credential__MlsCredential_basicPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )
        >
      >('frbgen_openmls_wire__crate__api__credential__MlsCredential_basic');
  late final _wire__crate__api__credential__MlsCredential_basic =
      _wire__crate__api__credential__MlsCredential_basicPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__credential__MlsCredential_certificates(
    int that,
  ) {
    return _wire__crate__api__credential__MlsCredential_certificates(that);
  }

  late final _wire__crate__api__credential__MlsCredential_certificatesPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function(ffi.UintPtr)>>(
        'frbgen_openmls_wire__crate__api__credential__MlsCredential_certificates',
      );
  late final _wire__crate__api__credential__MlsCredential_certificates =
      _wire__crate__api__credential__MlsCredential_certificatesPtr
          .asFunction<WireSyncRust2DartDco Function(int)>();

  WireSyncRust2DartDco
  wire__crate__api__credential__MlsCredential_credential_type(int that) {
    return _wire__crate__api__credential__MlsCredential_credential_type(that);
  }

  late final _wire__crate__api__credential__MlsCredential_credential_typePtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function(ffi.UintPtr)>>(
        'frbgen_openmls_wire__crate__api__credential__MlsCredential_credential_type',
      );
  late final _wire__crate__api__credential__MlsCredential_credential_type =
      _wire__crate__api__credential__MlsCredential_credential_typePtr
          .asFunction<WireSyncRust2DartDco Function(int)>();

  WireSyncRust2DartDco wire__crate__api__credential__MlsCredential_deserialize(
    ffi.Pointer<wire_cst_list_prim_u_8_loose> bytes,
  ) {
    return _wire__crate__api__credential__MlsCredential_deserialize(bytes);
  }

  late final _wire__crate__api__credential__MlsCredential_deserializePtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )
        >
      >(
        'frbgen_openmls_wire__crate__api__credential__MlsCredential_deserialize',
      );
  late final _wire__crate__api__credential__MlsCredential_deserialize =
      _wire__crate__api__credential__MlsCredential_deserializePtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__credential__MlsCredential_identity(
    int that,
  ) {
    return _wire__crate__api__credential__MlsCredential_identity(that);
  }

  late final _wire__crate__api__credential__MlsCredential_identityPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function(ffi.UintPtr)>>(
        'frbgen_openmls_wire__crate__api__credential__MlsCredential_identity',
      );
  late final _wire__crate__api__credential__MlsCredential_identity =
      _wire__crate__api__credential__MlsCredential_identityPtr
          .asFunction<WireSyncRust2DartDco Function(int)>();

  WireSyncRust2DartDco wire__crate__api__credential__MlsCredential_serialize(
    int that,
  ) {
    return _wire__crate__api__credential__MlsCredential_serialize(that);
  }

  late final _wire__crate__api__credential__MlsCredential_serializePtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function(ffi.UintPtr)>>(
        'frbgen_openmls_wire__crate__api__credential__MlsCredential_serialize',
      );
  late final _wire__crate__api__credential__MlsCredential_serialize =
      _wire__crate__api__credential__MlsCredential_serializePtr
          .asFunction<WireSyncRust2DartDco Function(int)>();

  WireSyncRust2DartDco
  wire__crate__api__credential__MlsCredential_serialized_content(int that) {
    return _wire__crate__api__credential__MlsCredential_serialized_content(
      that,
    );
  }

  late final _wire__crate__api__credential__MlsCredential_serialized_contentPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function(ffi.UintPtr)>>(
        'frbgen_openmls_wire__crate__api__credential__MlsCredential_serialized_content',
      );
  late final _wire__crate__api__credential__MlsCredential_serialized_content =
      _wire__crate__api__credential__MlsCredential_serialized_contentPtr
          .asFunction<WireSyncRust2DartDco Function(int)>();

  WireSyncRust2DartDco wire__crate__api__credential__MlsCredential_x509(
    ffi.Pointer<wire_cst_list_list_prim_u_8_strict> certificate_chain,
  ) {
    return _wire__crate__api__credential__MlsCredential_x509(certificate_chain);
  }

  late final _wire__crate__api__credential__MlsCredential_x509Ptr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_list_prim_u_8_strict>,
          )
        >
      >('frbgen_openmls_wire__crate__api__credential__MlsCredential_x509');
  late final _wire__crate__api__credential__MlsCredential_x509 =
      _wire__crate__api__credential__MlsCredential_x509Ptr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_list_prim_u_8_strict>,
            )
          >();

  WireSyncRust2DartDco
  wire__crate__api__keys__MlsSignatureKeyPair_deserialize_public(
    ffi.Pointer<wire_cst_list_prim_u_8_loose> bytes,
  ) {
    return _wire__crate__api__keys__MlsSignatureKeyPair_deserialize_public(
      bytes,
    );
  }

  late final _wire__crate__api__keys__MlsSignatureKeyPair_deserialize_publicPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )
        >
      >(
        'frbgen_openmls_wire__crate__api__keys__MlsSignatureKeyPair_deserialize_public',
      );
  late final _wire__crate__api__keys__MlsSignatureKeyPair_deserialize_public =
      _wire__crate__api__keys__MlsSignatureKeyPair_deserialize_publicPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__keys__MlsSignatureKeyPair_from_raw(
    int ciphersuite,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> private_key,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> public_key,
  ) {
    return _wire__crate__api__keys__MlsSignatureKeyPair_from_raw(
      ciphersuite,
      private_key,
      public_key,
    );
  }

  late final _wire__crate__api__keys__MlsSignatureKeyPair_from_rawPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Int32,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )
        >
      >('frbgen_openmls_wire__crate__api__keys__MlsSignatureKeyPair_from_raw');
  late final _wire__crate__api__keys__MlsSignatureKeyPair_from_raw =
      _wire__crate__api__keys__MlsSignatureKeyPair_from_rawPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__keys__MlsSignatureKeyPair_generate(
    int ciphersuite,
  ) {
    return _wire__crate__api__keys__MlsSignatureKeyPair_generate(ciphersuite);
  }

  late final _wire__crate__api__keys__MlsSignatureKeyPair_generatePtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function(ffi.Int32)>>(
        'frbgen_openmls_wire__crate__api__keys__MlsSignatureKeyPair_generate',
      );
  late final _wire__crate__api__keys__MlsSignatureKeyPair_generate =
      _wire__crate__api__keys__MlsSignatureKeyPair_generatePtr
          .asFunction<WireSyncRust2DartDco Function(int)>();

  WireSyncRust2DartDco wire__crate__api__keys__MlsSignatureKeyPair_private_key(
    int that,
  ) {
    return _wire__crate__api__keys__MlsSignatureKeyPair_private_key(that);
  }

  late final _wire__crate__api__keys__MlsSignatureKeyPair_private_keyPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function(ffi.UintPtr)>>(
        'frbgen_openmls_wire__crate__api__keys__MlsSignatureKeyPair_private_key',
      );
  late final _wire__crate__api__keys__MlsSignatureKeyPair_private_key =
      _wire__crate__api__keys__MlsSignatureKeyPair_private_keyPtr
          .asFunction<WireSyncRust2DartDco Function(int)>();

  WireSyncRust2DartDco wire__crate__api__keys__MlsSignatureKeyPair_public_key(
    int that,
  ) {
    return _wire__crate__api__keys__MlsSignatureKeyPair_public_key(that);
  }

  late final _wire__crate__api__keys__MlsSignatureKeyPair_public_keyPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function(ffi.UintPtr)>>(
        'frbgen_openmls_wire__crate__api__keys__MlsSignatureKeyPair_public_key',
      );
  late final _wire__crate__api__keys__MlsSignatureKeyPair_public_key =
      _wire__crate__api__keys__MlsSignatureKeyPair_public_keyPtr
          .asFunction<WireSyncRust2DartDco Function(int)>();

  WireSyncRust2DartDco wire__crate__api__keys__MlsSignatureKeyPair_serialize(
    int that,
  ) {
    return _wire__crate__api__keys__MlsSignatureKeyPair_serialize(that);
  }

  late final _wire__crate__api__keys__MlsSignatureKeyPair_serializePtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function(ffi.UintPtr)>>(
        'frbgen_openmls_wire__crate__api__keys__MlsSignatureKeyPair_serialize',
      );
  late final _wire__crate__api__keys__MlsSignatureKeyPair_serialize =
      _wire__crate__api__keys__MlsSignatureKeyPair_serializePtr
          .asFunction<WireSyncRust2DartDco Function(int)>();

  WireSyncRust2DartDco
  wire__crate__api__keys__MlsSignatureKeyPair_signature_scheme(int that) {
    return _wire__crate__api__keys__MlsSignatureKeyPair_signature_scheme(that);
  }

  late final _wire__crate__api__keys__MlsSignatureKeyPair_signature_schemePtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function(ffi.UintPtr)>>(
        'frbgen_openmls_wire__crate__api__keys__MlsSignatureKeyPair_signature_scheme',
      );
  late final _wire__crate__api__keys__MlsSignatureKeyPair_signature_scheme =
      _wire__crate__api__keys__MlsSignatureKeyPair_signature_schemePtr
          .asFunction<WireSyncRust2DartDco Function(int)>();

  void wire__crate__api__storage__add_members_with_storage(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> group_id,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> signer_bytes,
    ffi.Pointer<wire_cst_list_list_prim_u_8_strict> key_packages_bytes,
    ffi.Pointer<wire_cst_list_list_prim_u_8_strict>
    expected_credential_identities,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> aad,
    ffi.Pointer<wire_cst_list_mls_storage_entry> storage_entries,
    int storage_format_version,
  ) {
    return _wire__crate__api__storage__add_members_with_storage(
      port_,
      group_id,
      signer_bytes,
      key_packages_bytes,
      expected_credential_identities,
      aad,
      storage_entries,
      storage_format_version,
    );
  }

  late final _wire__crate__api__storage__add_members_with_storagePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_mls_storage_entry>,
            ffi.Uint32,
          )
        >
      >('frbgen_openmls_wire__crate__api__storage__add_members_with_storage');
  late final _wire__crate__api__storage__add_members_with_storage =
      _wire__crate__api__storage__add_members_with_storagePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_mls_storage_entry>,
              int,
            )
          >();

  void wire__crate__api__storage__create_group_with_storage(
    int port_,
    ffi.Pointer<wire_cst_mls_group_config> config,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> signer_bytes,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> credential_identity,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> signer_public_key,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> group_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> credential_bytes,
    ffi.Pointer<wire_cst_list_mls_storage_entry> storage_entries,
    int storage_format_version,
  ) {
    return _wire__crate__api__storage__create_group_with_storage(
      port_,
      config,
      signer_bytes,
      credential_identity,
      signer_public_key,
      group_id,
      credential_bytes,
      storage_entries,
      storage_format_version,
    );
  }

  late final _wire__crate__api__storage__create_group_with_storagePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_mls_group_config>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_mls_storage_entry>,
            ffi.Uint32,
          )
        >
      >('frbgen_openmls_wire__crate__api__storage__create_group_with_storage');
  late final _wire__crate__api__storage__create_group_with_storage =
      _wire__crate__api__storage__create_group_with_storagePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_mls_group_config>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_mls_storage_entry>,
              int,
            )
          >();

  void wire__crate__api__storage__create_key_package_with_storage(
    int port_,
    int ciphersuite,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> signer_bytes,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> credential_identity,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> signer_public_key,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> credential_bytes,
    ffi.Pointer<wire_cst_list_mls_storage_entry> storage_entries,
    int storage_format_version,
  ) {
    return _wire__crate__api__storage__create_key_package_with_storage(
      port_,
      ciphersuite,
      signer_bytes,
      credential_identity,
      signer_public_key,
      credential_bytes,
      storage_entries,
      storage_format_version,
    );
  }

  late final _wire__crate__api__storage__create_key_package_with_storagePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Int32,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_mls_storage_entry>,
            ffi.Uint32,
          )
        >
      >(
        'frbgen_openmls_wire__crate__api__storage__create_key_package_with_storage',
      );
  late final _wire__crate__api__storage__create_key_package_with_storage =
      _wire__crate__api__storage__create_key_package_with_storagePtr
          .asFunction<
            void Function(
              int,
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_mls_storage_entry>,
              int,
            )
          >();

  void wire__crate__api__storage__create_message_with_storage(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> group_id,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> signer_bytes,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> message,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> aad,
    ffi.Pointer<wire_cst_list_mls_storage_entry> storage_entries,
    int storage_format_version,
  ) {
    return _wire__crate__api__storage__create_message_with_storage(
      port_,
      group_id,
      signer_bytes,
      message,
      aad,
      storage_entries,
      storage_format_version,
    );
  }

  late final _wire__crate__api__storage__create_message_with_storagePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_mls_storage_entry>,
            ffi.Uint32,
          )
        >
      >(
        'frbgen_openmls_wire__crate__api__storage__create_message_with_storage',
      );
  late final _wire__crate__api__storage__create_message_with_storage =
      _wire__crate__api__storage__create_message_with_storagePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_mls_storage_entry>,
              int,
            )
          >();

  void wire__crate__api__storage__delete_group_with_storage(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> group_id,
    ffi.Pointer<wire_cst_list_mls_storage_entry> storage_entries,
    int storage_format_version,
  ) {
    return _wire__crate__api__storage__delete_group_with_storage(
      port_,
      group_id,
      storage_entries,
      storage_format_version,
    );
  }

  late final _wire__crate__api__storage__delete_group_with_storagePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_mls_storage_entry>,
            ffi.Uint32,
          )
        >
      >('frbgen_openmls_wire__crate__api__storage__delete_group_with_storage');
  late final _wire__crate__api__storage__delete_group_with_storage =
      _wire__crate__api__storage__delete_group_with_storagePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_mls_storage_entry>,
              int,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__init__init_openmls(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> _library_path,
  ) {
    return _wire__crate__api__init__init_openmls(_library_path);
  }

  late final _wire__crate__api__init__init_openmlsPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_openmls_wire__crate__api__init__init_openmls');
  late final _wire__crate__api__init__init_openmls =
      _wire__crate__api__init__init_openmlsPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__init__is_openmls_initialized() {
    return _wire__crate__api__init__is_openmls_initialized();
  }

  late final _wire__crate__api__init__is_openmls_initializedPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_openmls_wire__crate__api__init__is_openmls_initialized',
      );
  late final _wire__crate__api__init__is_openmls_initialized =
      _wire__crate__api__init__is_openmls_initializedPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  void wire__crate__api__storage__join_group_from_welcome_with_storage(
    int port_,
    ffi.Pointer<wire_cst_mls_group_config> config,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> welcome_bytes,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> ratchet_tree_bytes,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> signer_bytes,
    ffi.Pointer<wire_cst_list_mls_storage_entry> storage_entries,
    int storage_format_version,
  ) {
    return _wire__crate__api__storage__join_group_from_welcome_with_storage(
      port_,
      config,
      welcome_bytes,
      ratchet_tree_bytes,
      signer_bytes,
      storage_entries,
      storage_format_version,
    );
  }

  late final _wire__crate__api__storage__join_group_from_welcome_with_storagePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_mls_group_config>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_mls_storage_entry>,
            ffi.Uint32,
          )
        >
      >(
        'frbgen_openmls_wire__crate__api__storage__join_group_from_welcome_with_storage',
      );
  late final _wire__crate__api__storage__join_group_from_welcome_with_storage =
      _wire__crate__api__storage__join_group_from_welcome_with_storagePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_mls_group_config>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_mls_storage_entry>,
              int,
            )
          >();

  WireSyncRust2DartDco
  wire__crate__api__config__mls_group_config_default_config(int ciphersuite) {
    return _wire__crate__api__config__mls_group_config_default_config(
      ciphersuite,
    );
  }

  late final _wire__crate__api__config__mls_group_config_default_configPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function(ffi.Int32)>>(
        'frbgen_openmls_wire__crate__api__config__mls_group_config_default_config',
      );
  late final _wire__crate__api__config__mls_group_config_default_config =
      _wire__crate__api__config__mls_group_config_default_configPtr
          .asFunction<WireSyncRust2DartDco Function(int)>();

  WireSyncRust2DartDco wire__crate__api__message__mls_message_content_type(
    ffi.Pointer<wire_cst_list_prim_u_8_loose> message_bytes,
  ) {
    return _wire__crate__api__message__mls_message_content_type(message_bytes);
  }

  late final _wire__crate__api__message__mls_message_content_typePtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )
        >
      >('frbgen_openmls_wire__crate__api__message__mls_message_content_type');
  late final _wire__crate__api__message__mls_message_content_type =
      _wire__crate__api__message__mls_message_content_typePtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__message__mls_message_extract_epoch(
    ffi.Pointer<wire_cst_list_prim_u_8_loose> message_bytes,
  ) {
    return _wire__crate__api__message__mls_message_extract_epoch(message_bytes);
  }

  late final _wire__crate__api__message__mls_message_extract_epochPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )
        >
      >('frbgen_openmls_wire__crate__api__message__mls_message_extract_epoch');
  late final _wire__crate__api__message__mls_message_extract_epoch =
      _wire__crate__api__message__mls_message_extract_epochPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__message__mls_message_extract_group_id(
    ffi.Pointer<wire_cst_list_prim_u_8_loose> message_bytes,
  ) {
    return _wire__crate__api__message__mls_message_extract_group_id(
      message_bytes,
    );
  }

  late final _wire__crate__api__message__mls_message_extract_group_idPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )
        >
      >(
        'frbgen_openmls_wire__crate__api__message__mls_message_extract_group_id',
      );
  late final _wire__crate__api__message__mls_message_extract_group_id =
      _wire__crate__api__message__mls_message_extract_group_idPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__storage__mls_storage_format_version() {
    return _wire__crate__api__storage__mls_storage_format_version();
  }

  late final _wire__crate__api__storage__mls_storage_format_versionPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_openmls_wire__crate__api__storage__mls_storage_format_version',
      );
  late final _wire__crate__api__storage__mls_storage_format_version =
      _wire__crate__api__storage__mls_storage_format_versionPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  void wire__crate__api__storage__process_message_with_storage(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> group_id,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> message_bytes,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> expected_aad,
    ffi.Pointer<wire_cst_list_mls_storage_entry> storage_entries,
    int storage_format_version,
  ) {
    return _wire__crate__api__storage__process_message_with_storage(
      port_,
      group_id,
      message_bytes,
      expected_aad,
      storage_entries,
      storage_format_version,
    );
  }

  late final _wire__crate__api__storage__process_message_with_storagePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_mls_storage_entry>,
            ffi.Uint32,
          )
        >
      >(
        'frbgen_openmls_wire__crate__api__storage__process_message_with_storage',
      );
  late final _wire__crate__api__storage__process_message_with_storage =
      _wire__crate__api__storage__process_message_with_storagePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_mls_storage_entry>,
              int,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__keys__serialize_signer(
    int ciphersuite,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> private_key,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> public_key,
  ) {
    return _wire__crate__api__keys__serialize_signer(
      ciphersuite,
      private_key,
      public_key,
    );
  }

  late final _wire__crate__api__keys__serialize_signerPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Int32,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )
        >
      >('frbgen_openmls_wire__crate__api__keys__serialize_signer');
  late final _wire__crate__api__keys__serialize_signer =
      _wire__crate__api__keys__serialize_signerPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__types__supported_ciphersuites() {
    return _wire__crate__api__types__supported_ciphersuites();
  }

  late final _wire__crate__api__types__supported_ciphersuitesPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_openmls_wire__crate__api__types__supported_ciphersuites',
      );
  late final _wire__crate__api__types__supported_ciphersuites =
      _wire__crate__api__types__supported_ciphersuitesPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredentialPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_openmls_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredentialPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredentialPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_openmls_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredentialPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPairPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_openmls_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPairPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPairPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_openmls_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPairPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<wire_cst_mls_group_config>
  cst_new_box_autoadd_mls_group_config() {
    return _cst_new_box_autoadd_mls_group_config();
  }

  late final _cst_new_box_autoadd_mls_group_configPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<wire_cst_mls_group_config> Function()>
      >('frbgen_openmls_cst_new_box_autoadd_mls_group_config');
  late final _cst_new_box_autoadd_mls_group_config =
      _cst_new_box_autoadd_mls_group_configPtr
          .asFunction<ffi.Pointer<wire_cst_mls_group_config> Function()>();

  ffi.Pointer<ffi.Int32> cst_new_box_autoadd_mls_proposal_type(int value) {
    return _cst_new_box_autoadd_mls_proposal_type(value);
  }

  late final _cst_new_box_autoadd_mls_proposal_typePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Int32> Function(ffi.Int32)>>(
        'frbgen_openmls_cst_new_box_autoadd_mls_proposal_type',
      );
  late final _cst_new_box_autoadd_mls_proposal_type =
      _cst_new_box_autoadd_mls_proposal_typePtr
          .asFunction<ffi.Pointer<ffi.Int32> Function(int)>();

  ffi.Pointer<ffi.Uint32> cst_new_box_autoadd_u_32(int value) {
    return _cst_new_box_autoadd_u_32(value);
  }

  late final _cst_new_box_autoadd_u_32Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Uint32> Function(ffi.Uint32)>>(
        'frbgen_openmls_cst_new_box_autoadd_u_32',
      );
  late final _cst_new_box_autoadd_u_32 = _cst_new_box_autoadd_u_32Ptr
      .asFunction<ffi.Pointer<ffi.Uint32> Function(int)>();

  ffi.Pointer<wire_cst_list_list_prim_u_8_strict>
  cst_new_list_list_prim_u_8_strict(int len) {
    return _cst_new_list_list_prim_u_8_strict(len);
  }

  late final _cst_new_list_list_prim_u_8_strictPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_list_prim_u_8_strict> Function(ffi.Int32)
        >
      >('frbgen_openmls_cst_new_list_list_prim_u_8_strict');
  late final _cst_new_list_list_prim_u_8_strict =
      _cst_new_list_list_prim_u_8_strictPtr
          .asFunction<
            ffi.Pointer<wire_cst_list_list_prim_u_8_strict> Function(int)
          >();

  ffi.Pointer<wire_cst_list_mls_ciphersuite> cst_new_list_mls_ciphersuite(
    int len,
  ) {
    return _cst_new_list_mls_ciphersuite(len);
  }

  late final _cst_new_list_mls_ciphersuitePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_mls_ciphersuite> Function(ffi.Int32)
        >
      >('frbgen_openmls_cst_new_list_mls_ciphersuite');
  late final _cst_new_list_mls_ciphersuite = _cst_new_list_mls_ciphersuitePtr
      .asFunction<ffi.Pointer<wire_cst_list_mls_ciphersuite> Function(int)>();

  ffi.Pointer<wire_cst_list_mls_storage_entry> cst_new_list_mls_storage_entry(
    int len,
  ) {
    return _cst_new_list_mls_storage_entry(len);
  }

  late final _cst_new_list_mls_storage_entryPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_mls_storage_entry> Function(ffi.Int32)
        >
      >('frbgen_openmls_cst_new_list_mls_storage_entry');
  late final _cst_new_list_mls_storage_entry =
      _cst_new_list_mls_storage_entryPtr
          .asFunction<
            ffi.Pointer<wire_cst_list_mls_storage_entry> Function(int)
          >();

  ffi.Pointer<wire_cst_list_prim_u_8_loose> cst_new_list_prim_u_8_loose(
    int len,
  ) {
    return _cst_new_list_prim_u_8_loose(len);
  }

  late final _cst_new_list_prim_u_8_loosePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_loose> Function(ffi.Int32)
        >
      >('frbgen_openmls_cst_new_list_prim_u_8_loose');
  late final _cst_new_list_prim_u_8_loose = _cst_new_list_prim_u_8_loosePtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_loose> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_new_list_prim_u_8_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_8_strict(len);
  }

  late final _cst_new_list_prim_u_8_strictPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(ffi.Int32)
        >
      >('frbgen_openmls_cst_new_list_prim_u_8_strict');
  late final _cst_new_list_prim_u_8_strict = _cst_new_list_prim_u_8_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(int)>();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
        'dummy_method_to_enforce_bundling',
      );
  late final _dummy_method_to_enforce_bundling =
      _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();
}

typedef DartPort = ffi.Int64;
typedef DartDartPort = int;
typedef DartPostCObjectFnTypeFunction =
    ffi.Bool Function(DartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartDartPostCObjectFnTypeFunction =
    bool Function(DartDartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartPostCObjectFnType =
    ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnTypeFunction>>;

final class wire_cst_list_prim_u_8_loose extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Pointer<wire_cst_list_prim_u_8_strict>> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_mls_storage_entry extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> key;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> value;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> group_id;
}

final class wire_cst_list_mls_storage_entry extends ffi.Struct {
  external ffi.Pointer<wire_cst_mls_storage_entry> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_mls_group_config extends ffi.Struct {
  @ffi.Int32()
  external int ciphersuite;

  @ffi.Int32()
  external int wire_format_policy;

  @ffi.Bool()
  external bool use_ratchet_tree_extension;

  @ffi.Uint32()
  external int max_past_epochs;

  @ffi.Uint32()
  external int padding_size;

  @ffi.Uint32()
  external int sender_ratchet_max_out_of_order;

  @ffi.Uint32()
  external int sender_ratchet_max_forward_distance;

  @ffi.Uint32()
  external int number_of_resumption_psks;
}

final class wire_cst_list_mls_ciphersuite extends ffi.Struct {
  external ffi.Pointer<ffi.Int32> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_mls_storage_batch extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_mls_storage_entry> upserts;

  external ffi.Pointer<wire_cst_list_list_prim_u_8_strict> deletes;

  external ffi.Pointer<wire_cst_list_list_prim_u_8_strict> deleted_group_ids;

  @ffi.Uint32()
  external int storage_format_version;
}

final class wire_cst_add_members_with_storage_result extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> commit;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> welcome;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> group_info;

  external wire_cst_mls_storage_batch storage_batch;
}

final class wire_cst_create_group_with_storage_result extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> group_id;

  external wire_cst_mls_storage_batch storage_batch;
}

final class wire_cst_create_key_package_with_storage_result extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> key_package_bytes;

  external wire_cst_mls_storage_batch storage_batch;
}

final class wire_cst_create_message_with_storage_result extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> ciphertext;

  external wire_cst_mls_storage_batch storage_batch;
}

final class wire_cst_join_group_with_storage_result extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> group_id;

  external wire_cst_mls_storage_batch storage_batch;
}

final class wire_cst_process_message_with_storage_result extends ffi.Struct {
  @ffi.Int32()
  external int message_type;

  external ffi.Pointer<ffi.Uint32> sender_index;

  @ffi.Uint64()
  external int previous_epoch;

  @ffi.Uint64()
  external int resulting_epoch;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> application_message;

  @ffi.Bool()
  external bool has_staged_commit;

  @ffi.Bool()
  external bool has_proposal;

  external ffi.Pointer<ffi.Int32> proposal_type;

  external wire_cst_mls_storage_batch storage_batch;
}

const int MLS_STORAGE_FORMAT_VERSION = 1;
