// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/config.dart';
import 'api/credential.dart';
import 'api/init.dart';
import 'api/keys.dart';
import 'api/message.dart';
import 'api/storage.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -159701412;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'openmls_frb',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  MlsCredential crateApiCredentialMlsCredentialBasic({
    required List<int> identity,
  });

  List<Uint8List> crateApiCredentialMlsCredentialCertificates({
    required MlsCredential that,
  });

  int crateApiCredentialMlsCredentialCredentialType({
    required MlsCredential that,
  });

  MlsCredential crateApiCredentialMlsCredentialDeserialize({
    required List<int> bytes,
  });

  Uint8List crateApiCredentialMlsCredentialIdentity({
    required MlsCredential that,
  });

  Uint8List crateApiCredentialMlsCredentialSerialize({
    required MlsCredential that,
  });

  Uint8List crateApiCredentialMlsCredentialSerializedContent({
    required MlsCredential that,
  });

  MlsCredential crateApiCredentialMlsCredentialX509({
    required List<Uint8List> certificateChain,
  });

  MlsSignatureKeyPair crateApiKeysMlsSignatureKeyPairDeserializePublic({
    required List<int> bytes,
  });

  MlsSignatureKeyPair crateApiKeysMlsSignatureKeyPairFromRaw({
    required MlsCiphersuite ciphersuite,
    required List<int> privateKey,
    required List<int> publicKey,
  });

  MlsSignatureKeyPair crateApiKeysMlsSignatureKeyPairGenerate({
    required MlsCiphersuite ciphersuite,
  });

  Uint8List crateApiKeysMlsSignatureKeyPairPrivateKey({
    required MlsSignatureKeyPair that,
  });

  Uint8List crateApiKeysMlsSignatureKeyPairPublicKey({
    required MlsSignatureKeyPair that,
  });

  Uint8List crateApiKeysMlsSignatureKeyPairSerialize({
    required MlsSignatureKeyPair that,
  });

  int crateApiKeysMlsSignatureKeyPairSignatureScheme({
    required MlsSignatureKeyPair that,
  });

  Future<AddMembersWithStorageResult> crateApiStorageAddMembersWithStorage({
    required List<int> groupId,
    required List<int> signerBytes,
    required List<Uint8List> keyPackagesBytes,
    required List<Uint8List> expectedCredentialIdentities,
    required List<int> aad,
    required List<MlsStorageEntry> storageEntries,
    required int storageFormatVersion,
  });

  Future<CreateGroupWithStorageResult> crateApiStorageCreateGroupWithStorage({
    required MlsGroupConfig config,
    required List<int> signerBytes,
    required List<int> credentialIdentity,
    required List<int> signerPublicKey,
    Uint8List? groupId,
    Uint8List? credentialBytes,
    required List<MlsStorageEntry> storageEntries,
    required int storageFormatVersion,
  });

  Future<CreateKeyPackageWithStorageResult>
  crateApiStorageCreateKeyPackageWithStorage({
    required MlsCiphersuite ciphersuite,
    required List<int> signerBytes,
    required List<int> credentialIdentity,
    required List<int> signerPublicKey,
    Uint8List? credentialBytes,
    required List<MlsStorageEntry> storageEntries,
    required int storageFormatVersion,
  });

  Future<CreateMessageWithStorageResult>
  crateApiStorageCreateMessageWithStorage({
    required List<int> groupId,
    required List<int> signerBytes,
    required List<int> message,
    required List<int> aad,
    required List<MlsStorageEntry> storageEntries,
    required int storageFormatVersion,
  });

  Future<MlsStorageBatch> crateApiStorageDeleteGroupWithStorage({
    required List<int> groupId,
    required List<MlsStorageEntry> storageEntries,
    required int storageFormatVersion,
  });

  void crateApiInitInitOpenmls({required String libraryPath});

  bool crateApiInitIsOpenmlsInitialized();

  Future<JoinGroupWithStorageResult>
  crateApiStorageJoinGroupFromWelcomeWithStorage({
    required MlsGroupConfig config,
    required List<int> welcomeBytes,
    Uint8List? ratchetTreeBytes,
    required List<int> signerBytes,
    required List<MlsStorageEntry> storageEntries,
    required int storageFormatVersion,
  });

  MlsGroupConfig crateApiConfigMlsGroupConfigDefaultConfig({
    required MlsCiphersuite ciphersuite,
  });

  String crateApiMessageMlsMessageContentType({
    required List<int> messageBytes,
  });

  BigInt crateApiMessageMlsMessageExtractEpoch({
    required List<int> messageBytes,
  });

  Uint8List crateApiMessageMlsMessageExtractGroupId({
    required List<int> messageBytes,
  });

  int crateApiStorageMlsStorageFormatVersion();

  Future<ProcessMessageWithStorageResult>
  crateApiStorageProcessMessageWithStorage({
    required List<int> groupId,
    required List<int> messageBytes,
    required List<int> expectedAad,
    required List<MlsStorageEntry> storageEntries,
    required int storageFormatVersion,
  });

  Uint8List crateApiKeysSerializeSigner({
    required MlsCiphersuite ciphersuite,
    required List<int> privateKey,
    required List<int> publicKey,
  });

  List<MlsCiphersuite> crateApiTypesSupportedCiphersuites();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_MlsCredential;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_MlsCredential;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_MlsCredentialPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_MlsSignatureKeyPair;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_MlsSignatureKeyPair;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_MlsSignatureKeyPairPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  MlsCredential crateApiCredentialMlsCredentialBasic({
    required List<int> identity,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_list_prim_u_8_loose(identity);
          return wire.wire__crate__api__credential__MlsCredential_basic(arg0);
        },
        codec: DcoCodec(
          decodeSuccessData:
              dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiCredentialMlsCredentialBasicConstMeta,
        argValues: [identity],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCredentialMlsCredentialBasicConstMeta =>
      const TaskConstMeta(
        debugName: "MlsCredential_basic",
        argNames: ["identity"],
      );

  @override
  List<Uint8List> crateApiCredentialMlsCredentialCertificates({
    required MlsCredential that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
                that,
              );
          return wire.wire__crate__api__credential__MlsCredential_certificates(
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_list_prim_u_8_strict,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiCredentialMlsCredentialCertificatesConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCredentialMlsCredentialCertificatesConstMeta =>
      const TaskConstMeta(
        debugName: "MlsCredential_certificates",
        argNames: ["that"],
      );

  @override
  int crateApiCredentialMlsCredentialCredentialType({
    required MlsCredential that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
                that,
              );
          return wire
              .wire__crate__api__credential__MlsCredential_credential_type(
                arg0,
              );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_u_16,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCredentialMlsCredentialCredentialTypeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCredentialMlsCredentialCredentialTypeConstMeta =>
      const TaskConstMeta(
        debugName: "MlsCredential_credential_type",
        argNames: ["that"],
      );

  @override
  MlsCredential crateApiCredentialMlsCredentialDeserialize({
    required List<int> bytes,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_list_prim_u_8_loose(bytes);
          return wire.wire__crate__api__credential__MlsCredential_deserialize(
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData:
              dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiCredentialMlsCredentialDeserializeConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCredentialMlsCredentialDeserializeConstMeta =>
      const TaskConstMeta(
        debugName: "MlsCredential_deserialize",
        argNames: ["bytes"],
      );

  @override
  Uint8List crateApiCredentialMlsCredentialIdentity({
    required MlsCredential that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
                that,
              );
          return wire.wire__crate__api__credential__MlsCredential_identity(
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_prim_u_8_strict,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiCredentialMlsCredentialIdentityConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCredentialMlsCredentialIdentityConstMeta =>
      const TaskConstMeta(
        debugName: "MlsCredential_identity",
        argNames: ["that"],
      );

  @override
  Uint8List crateApiCredentialMlsCredentialSerialize({
    required MlsCredential that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
                that,
              );
          return wire.wire__crate__api__credential__MlsCredential_serialize(
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_prim_u_8_strict,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiCredentialMlsCredentialSerializeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCredentialMlsCredentialSerializeConstMeta =>
      const TaskConstMeta(
        debugName: "MlsCredential_serialize",
        argNames: ["that"],
      );

  @override
  Uint8List crateApiCredentialMlsCredentialSerializedContent({
    required MlsCredential that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
                that,
              );
          return wire
              .wire__crate__api__credential__MlsCredential_serialized_content(
                arg0,
              );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCredentialMlsCredentialSerializedContentConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiCredentialMlsCredentialSerializedContentConstMeta =>
      const TaskConstMeta(
        debugName: "MlsCredential_serialized_content",
        argNames: ["that"],
      );

  @override
  MlsCredential crateApiCredentialMlsCredentialX509({
    required List<Uint8List> certificateChain,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_list_list_prim_u_8_strict(certificateChain);
          return wire.wire__crate__api__credential__MlsCredential_x509(arg0);
        },
        codec: DcoCodec(
          decodeSuccessData:
              dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiCredentialMlsCredentialX509ConstMeta,
        argValues: [certificateChain],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCredentialMlsCredentialX509ConstMeta =>
      const TaskConstMeta(
        debugName: "MlsCredential_x509",
        argNames: ["certificateChain"],
      );

  @override
  MlsSignatureKeyPair crateApiKeysMlsSignatureKeyPairDeserializePublic({
    required List<int> bytes,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_list_prim_u_8_loose(bytes);
          return wire
              .wire__crate__api__keys__MlsSignatureKeyPair_deserialize_public(
                arg0,
              );
        },
        codec: DcoCodec(
          decodeSuccessData:
              dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiKeysMlsSignatureKeyPairDeserializePublicConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiKeysMlsSignatureKeyPairDeserializePublicConstMeta =>
      const TaskConstMeta(
        debugName: "MlsSignatureKeyPair_deserialize_public",
        argNames: ["bytes"],
      );

  @override
  MlsSignatureKeyPair crateApiKeysMlsSignatureKeyPairFromRaw({
    required MlsCiphersuite ciphersuite,
    required List<int> privateKey,
    required List<int> publicKey,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_mls_ciphersuite(ciphersuite);
          var arg1 = cst_encode_list_prim_u_8_loose(privateKey);
          var arg2 = cst_encode_list_prim_u_8_loose(publicKey);
          return wire.wire__crate__api__keys__MlsSignatureKeyPair_from_raw(
            arg0,
            arg1,
            arg2,
          );
        },
        codec: DcoCodec(
          decodeSuccessData:
              dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiKeysMlsSignatureKeyPairFromRawConstMeta,
        argValues: [ciphersuite, privateKey, publicKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKeysMlsSignatureKeyPairFromRawConstMeta =>
      const TaskConstMeta(
        debugName: "MlsSignatureKeyPair_from_raw",
        argNames: ["ciphersuite", "privateKey", "publicKey"],
      );

  @override
  MlsSignatureKeyPair crateApiKeysMlsSignatureKeyPairGenerate({
    required MlsCiphersuite ciphersuite,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_mls_ciphersuite(ciphersuite);
          return wire.wire__crate__api__keys__MlsSignatureKeyPair_generate(
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData:
              dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiKeysMlsSignatureKeyPairGenerateConstMeta,
        argValues: [ciphersuite],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKeysMlsSignatureKeyPairGenerateConstMeta =>
      const TaskConstMeta(
        debugName: "MlsSignatureKeyPair_generate",
        argNames: ["ciphersuite"],
      );

  @override
  Uint8List crateApiKeysMlsSignatureKeyPairPrivateKey({
    required MlsSignatureKeyPair that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
                that,
              );
          return wire.wire__crate__api__keys__MlsSignatureKeyPair_private_key(
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKeysMlsSignatureKeyPairPrivateKeyConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKeysMlsSignatureKeyPairPrivateKeyConstMeta =>
      const TaskConstMeta(
        debugName: "MlsSignatureKeyPair_private_key",
        argNames: ["that"],
      );

  @override
  Uint8List crateApiKeysMlsSignatureKeyPairPublicKey({
    required MlsSignatureKeyPair that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
                that,
              );
          return wire.wire__crate__api__keys__MlsSignatureKeyPair_public_key(
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKeysMlsSignatureKeyPairPublicKeyConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKeysMlsSignatureKeyPairPublicKeyConstMeta =>
      const TaskConstMeta(
        debugName: "MlsSignatureKeyPair_public_key",
        argNames: ["that"],
      );

  @override
  Uint8List crateApiKeysMlsSignatureKeyPairSerialize({
    required MlsSignatureKeyPair that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
                that,
              );
          return wire.wire__crate__api__keys__MlsSignatureKeyPair_serialize(
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_prim_u_8_strict,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiKeysMlsSignatureKeyPairSerializeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKeysMlsSignatureKeyPairSerializeConstMeta =>
      const TaskConstMeta(
        debugName: "MlsSignatureKeyPair_serialize",
        argNames: ["that"],
      );

  @override
  int crateApiKeysMlsSignatureKeyPairSignatureScheme({
    required MlsSignatureKeyPair that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 =
              cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
                that,
              );
          return wire
              .wire__crate__api__keys__MlsSignatureKeyPair_signature_scheme(
                arg0,
              );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_u_16,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKeysMlsSignatureKeyPairSignatureSchemeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKeysMlsSignatureKeyPairSignatureSchemeConstMeta =>
      const TaskConstMeta(
        debugName: "MlsSignatureKeyPair_signature_scheme",
        argNames: ["that"],
      );

  @override
  Future<AddMembersWithStorageResult> crateApiStorageAddMembersWithStorage({
    required List<int> groupId,
    required List<int> signerBytes,
    required List<Uint8List> keyPackagesBytes,
    required List<Uint8List> expectedCredentialIdentities,
    required List<int> aad,
    required List<MlsStorageEntry> storageEntries,
    required int storageFormatVersion,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_list_prim_u_8_loose(groupId);
          var arg1 = cst_encode_list_prim_u_8_loose(signerBytes);
          var arg2 = cst_encode_list_list_prim_u_8_strict(keyPackagesBytes);
          var arg3 = cst_encode_list_list_prim_u_8_strict(
            expectedCredentialIdentities,
          );
          var arg4 = cst_encode_list_prim_u_8_loose(aad);
          var arg5 = cst_encode_list_mls_storage_entry(storageEntries);
          var arg6 = cst_encode_u_32(storageFormatVersion);
          return wire.wire__crate__api__storage__add_members_with_storage(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
            arg5,
            arg6,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_add_members_with_storage_result,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiStorageAddMembersWithStorageConstMeta,
        argValues: [
          groupId,
          signerBytes,
          keyPackagesBytes,
          expectedCredentialIdentities,
          aad,
          storageEntries,
          storageFormatVersion,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageAddMembersWithStorageConstMeta =>
      const TaskConstMeta(
        debugName: "add_members_with_storage",
        argNames: [
          "groupId",
          "signerBytes",
          "keyPackagesBytes",
          "expectedCredentialIdentities",
          "aad",
          "storageEntries",
          "storageFormatVersion",
        ],
      );

  @override
  Future<CreateGroupWithStorageResult> crateApiStorageCreateGroupWithStorage({
    required MlsGroupConfig config,
    required List<int> signerBytes,
    required List<int> credentialIdentity,
    required List<int> signerPublicKey,
    Uint8List? groupId,
    Uint8List? credentialBytes,
    required List<MlsStorageEntry> storageEntries,
    required int storageFormatVersion,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_box_autoadd_mls_group_config(config);
          var arg1 = cst_encode_list_prim_u_8_loose(signerBytes);
          var arg2 = cst_encode_list_prim_u_8_loose(credentialIdentity);
          var arg3 = cst_encode_list_prim_u_8_loose(signerPublicKey);
          var arg4 = cst_encode_opt_list_prim_u_8_strict(groupId);
          var arg5 = cst_encode_opt_list_prim_u_8_strict(credentialBytes);
          var arg6 = cst_encode_list_mls_storage_entry(storageEntries);
          var arg7 = cst_encode_u_32(storageFormatVersion);
          return wire.wire__crate__api__storage__create_group_with_storage(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
            arg5,
            arg6,
            arg7,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_create_group_with_storage_result,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiStorageCreateGroupWithStorageConstMeta,
        argValues: [
          config,
          signerBytes,
          credentialIdentity,
          signerPublicKey,
          groupId,
          credentialBytes,
          storageEntries,
          storageFormatVersion,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageCreateGroupWithStorageConstMeta =>
      const TaskConstMeta(
        debugName: "create_group_with_storage",
        argNames: [
          "config",
          "signerBytes",
          "credentialIdentity",
          "signerPublicKey",
          "groupId",
          "credentialBytes",
          "storageEntries",
          "storageFormatVersion",
        ],
      );

  @override
  Future<CreateKeyPackageWithStorageResult>
  crateApiStorageCreateKeyPackageWithStorage({
    required MlsCiphersuite ciphersuite,
    required List<int> signerBytes,
    required List<int> credentialIdentity,
    required List<int> signerPublicKey,
    Uint8List? credentialBytes,
    required List<MlsStorageEntry> storageEntries,
    required int storageFormatVersion,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_mls_ciphersuite(ciphersuite);
          var arg1 = cst_encode_list_prim_u_8_loose(signerBytes);
          var arg2 = cst_encode_list_prim_u_8_loose(credentialIdentity);
          var arg3 = cst_encode_list_prim_u_8_loose(signerPublicKey);
          var arg4 = cst_encode_opt_list_prim_u_8_strict(credentialBytes);
          var arg5 = cst_encode_list_mls_storage_entry(storageEntries);
          var arg6 = cst_encode_u_32(storageFormatVersion);
          return wire
              .wire__crate__api__storage__create_key_package_with_storage(
                port_,
                arg0,
                arg1,
                arg2,
                arg3,
                arg4,
                arg5,
                arg6,
              );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_create_key_package_with_storage_result,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiStorageCreateKeyPackageWithStorageConstMeta,
        argValues: [
          ciphersuite,
          signerBytes,
          credentialIdentity,
          signerPublicKey,
          credentialBytes,
          storageEntries,
          storageFormatVersion,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageCreateKeyPackageWithStorageConstMeta =>
      const TaskConstMeta(
        debugName: "create_key_package_with_storage",
        argNames: [
          "ciphersuite",
          "signerBytes",
          "credentialIdentity",
          "signerPublicKey",
          "credentialBytes",
          "storageEntries",
          "storageFormatVersion",
        ],
      );

  @override
  Future<CreateMessageWithStorageResult>
  crateApiStorageCreateMessageWithStorage({
    required List<int> groupId,
    required List<int> signerBytes,
    required List<int> message,
    required List<int> aad,
    required List<MlsStorageEntry> storageEntries,
    required int storageFormatVersion,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_list_prim_u_8_loose(groupId);
          var arg1 = cst_encode_list_prim_u_8_loose(signerBytes);
          var arg2 = cst_encode_list_prim_u_8_loose(message);
          var arg3 = cst_encode_list_prim_u_8_loose(aad);
          var arg4 = cst_encode_list_mls_storage_entry(storageEntries);
          var arg5 = cst_encode_u_32(storageFormatVersion);
          return wire.wire__crate__api__storage__create_message_with_storage(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
            arg5,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_create_message_with_storage_result,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiStorageCreateMessageWithStorageConstMeta,
        argValues: [
          groupId,
          signerBytes,
          message,
          aad,
          storageEntries,
          storageFormatVersion,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageCreateMessageWithStorageConstMeta =>
      const TaskConstMeta(
        debugName: "create_message_with_storage",
        argNames: [
          "groupId",
          "signerBytes",
          "message",
          "aad",
          "storageEntries",
          "storageFormatVersion",
        ],
      );

  @override
  Future<MlsStorageBatch> crateApiStorageDeleteGroupWithStorage({
    required List<int> groupId,
    required List<MlsStorageEntry> storageEntries,
    required int storageFormatVersion,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_list_prim_u_8_loose(groupId);
          var arg1 = cst_encode_list_mls_storage_entry(storageEntries);
          var arg2 = cst_encode_u_32(storageFormatVersion);
          return wire.wire__crate__api__storage__delete_group_with_storage(
            port_,
            arg0,
            arg1,
            arg2,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_mls_storage_batch,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiStorageDeleteGroupWithStorageConstMeta,
        argValues: [groupId, storageEntries, storageFormatVersion],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageDeleteGroupWithStorageConstMeta =>
      const TaskConstMeta(
        debugName: "delete_group_with_storage",
        argNames: ["groupId", "storageEntries", "storageFormatVersion"],
      );

  @override
  void crateApiInitInitOpenmls({required String libraryPath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_String(libraryPath);
          return wire.wire__crate__api__init__init_openmls(arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiInitInitOpenmlsConstMeta,
        argValues: [libraryPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitInitOpenmlsConstMeta =>
      const TaskConstMeta(debugName: "init_openmls", argNames: ["libraryPath"]);

  @override
  bool crateApiInitIsOpenmlsInitialized() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          return wire.wire__crate__api__init__is_openmls_initialized();
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitIsOpenmlsInitializedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitIsOpenmlsInitializedConstMeta =>
      const TaskConstMeta(debugName: "is_openmls_initialized", argNames: []);

  @override
  Future<JoinGroupWithStorageResult>
  crateApiStorageJoinGroupFromWelcomeWithStorage({
    required MlsGroupConfig config,
    required List<int> welcomeBytes,
    Uint8List? ratchetTreeBytes,
    required List<int> signerBytes,
    required List<MlsStorageEntry> storageEntries,
    required int storageFormatVersion,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_box_autoadd_mls_group_config(config);
          var arg1 = cst_encode_list_prim_u_8_loose(welcomeBytes);
          var arg2 = cst_encode_opt_list_prim_u_8_strict(ratchetTreeBytes);
          var arg3 = cst_encode_list_prim_u_8_loose(signerBytes);
          var arg4 = cst_encode_list_mls_storage_entry(storageEntries);
          var arg5 = cst_encode_u_32(storageFormatVersion);
          return wire
              .wire__crate__api__storage__join_group_from_welcome_with_storage(
                port_,
                arg0,
                arg1,
                arg2,
                arg3,
                arg4,
                arg5,
              );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_join_group_with_storage_result,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiStorageJoinGroupFromWelcomeWithStorageConstMeta,
        argValues: [
          config,
          welcomeBytes,
          ratchetTreeBytes,
          signerBytes,
          storageEntries,
          storageFormatVersion,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageJoinGroupFromWelcomeWithStorageConstMeta =>
      const TaskConstMeta(
        debugName: "join_group_from_welcome_with_storage",
        argNames: [
          "config",
          "welcomeBytes",
          "ratchetTreeBytes",
          "signerBytes",
          "storageEntries",
          "storageFormatVersion",
        ],
      );

  @override
  MlsGroupConfig crateApiConfigMlsGroupConfigDefaultConfig({
    required MlsCiphersuite ciphersuite,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_mls_ciphersuite(ciphersuite);
          return wire.wire__crate__api__config__mls_group_config_default_config(
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_mls_group_config,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConfigMlsGroupConfigDefaultConfigConstMeta,
        argValues: [ciphersuite],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigMlsGroupConfigDefaultConfigConstMeta =>
      const TaskConstMeta(
        debugName: "mls_group_config_default_config",
        argNames: ["ciphersuite"],
      );

  @override
  String crateApiMessageMlsMessageContentType({
    required List<int> messageBytes,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_list_prim_u_8_loose(messageBytes);
          return wire.wire__crate__api__message__mls_message_content_type(arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiMessageMlsMessageContentTypeConstMeta,
        argValues: [messageBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessageMlsMessageContentTypeConstMeta =>
      const TaskConstMeta(
        debugName: "mls_message_content_type",
        argNames: ["messageBytes"],
      );

  @override
  BigInt crateApiMessageMlsMessageExtractEpoch({
    required List<int> messageBytes,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_list_prim_u_8_loose(messageBytes);
          return wire.wire__crate__api__message__mls_message_extract_epoch(
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_u_64,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiMessageMlsMessageExtractEpochConstMeta,
        argValues: [messageBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessageMlsMessageExtractEpochConstMeta =>
      const TaskConstMeta(
        debugName: "mls_message_extract_epoch",
        argNames: ["messageBytes"],
      );

  @override
  Uint8List crateApiMessageMlsMessageExtractGroupId({
    required List<int> messageBytes,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_list_prim_u_8_loose(messageBytes);
          return wire.wire__crate__api__message__mls_message_extract_group_id(
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_prim_u_8_strict,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiMessageMlsMessageExtractGroupIdConstMeta,
        argValues: [messageBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessageMlsMessageExtractGroupIdConstMeta =>
      const TaskConstMeta(
        debugName: "mls_message_extract_group_id",
        argNames: ["messageBytes"],
      );

  @override
  int crateApiStorageMlsStorageFormatVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          return wire.wire__crate__api__storage__mls_storage_format_version();
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStorageMlsStorageFormatVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageMlsStorageFormatVersionConstMeta =>
      const TaskConstMeta(
        debugName: "mls_storage_format_version",
        argNames: [],
      );

  @override
  Future<ProcessMessageWithStorageResult>
  crateApiStorageProcessMessageWithStorage({
    required List<int> groupId,
    required List<int> messageBytes,
    required List<int> expectedAad,
    required List<MlsStorageEntry> storageEntries,
    required int storageFormatVersion,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_list_prim_u_8_loose(groupId);
          var arg1 = cst_encode_list_prim_u_8_loose(messageBytes);
          var arg2 = cst_encode_list_prim_u_8_loose(expectedAad);
          var arg3 = cst_encode_list_mls_storage_entry(storageEntries);
          var arg4 = cst_encode_u_32(storageFormatVersion);
          return wire.wire__crate__api__storage__process_message_with_storage(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_process_message_with_storage_result,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiStorageProcessMessageWithStorageConstMeta,
        argValues: [
          groupId,
          messageBytes,
          expectedAad,
          storageEntries,
          storageFormatVersion,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageProcessMessageWithStorageConstMeta =>
      const TaskConstMeta(
        debugName: "process_message_with_storage",
        argNames: [
          "groupId",
          "messageBytes",
          "expectedAad",
          "storageEntries",
          "storageFormatVersion",
        ],
      );

  @override
  Uint8List crateApiKeysSerializeSigner({
    required MlsCiphersuite ciphersuite,
    required List<int> privateKey,
    required List<int> publicKey,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          var arg0 = cst_encode_mls_ciphersuite(ciphersuite);
          var arg1 = cst_encode_list_prim_u_8_loose(privateKey);
          var arg2 = cst_encode_list_prim_u_8_loose(publicKey);
          return wire.wire__crate__api__keys__serialize_signer(
            arg0,
            arg1,
            arg2,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_prim_u_8_strict,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiKeysSerializeSignerConstMeta,
        argValues: [ciphersuite, privateKey, publicKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKeysSerializeSignerConstMeta =>
      const TaskConstMeta(
        debugName: "serialize_signer",
        argNames: ["ciphersuite", "privateKey", "publicKey"],
      );

  @override
  List<MlsCiphersuite> crateApiTypesSupportedCiphersuites() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          return wire.wire__crate__api__types__supported_ciphersuites();
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_mls_ciphersuite,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTypesSupportedCiphersuitesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypesSupportedCiphersuitesConstMeta =>
      const TaskConstMeta(debugName: "supported_ciphersuites", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_MlsCredential => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_MlsCredential => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_MlsSignatureKeyPair => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_MlsSignatureKeyPair => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair;

  @protected
  MlsCredential
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MlsCredentialImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MlsSignatureKeyPair
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MlsSignatureKeyPairImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MlsCredential
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MlsCredentialImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MlsSignatureKeyPair
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MlsSignatureKeyPairImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MlsCredential
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MlsCredentialImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MlsSignatureKeyPair
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MlsSignatureKeyPairImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AddMembersWithStorageResult dco_decode_add_members_with_storage_result(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return AddMembersWithStorageResult(
      commit: dco_decode_list_prim_u_8_strict(arr[0]),
      welcome: dco_decode_list_prim_u_8_strict(arr[1]),
      groupInfo: dco_decode_opt_list_prim_u_8_strict(arr[2]),
      storageBatch: dco_decode_mls_storage_batch(arr[3]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  MlsGroupConfig dco_decode_box_autoadd_mls_group_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_mls_group_config(raw);
  }

  @protected
  MlsProposalType dco_decode_box_autoadd_mls_proposal_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_mls_proposal_type(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  CreateGroupWithStorageResult dco_decode_create_group_with_storage_result(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CreateGroupWithStorageResult(
      groupId: dco_decode_list_prim_u_8_strict(arr[0]),
      storageBatch: dco_decode_mls_storage_batch(arr[1]),
    );
  }

  @protected
  CreateKeyPackageWithStorageResult
  dco_decode_create_key_package_with_storage_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CreateKeyPackageWithStorageResult(
      keyPackageBytes: dco_decode_list_prim_u_8_strict(arr[0]),
      storageBatch: dco_decode_mls_storage_batch(arr[1]),
    );
  }

  @protected
  CreateMessageWithStorageResult dco_decode_create_message_with_storage_result(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CreateMessageWithStorageResult(
      ciphertext: dco_decode_list_prim_u_8_strict(arr[0]),
      storageBatch: dco_decode_mls_storage_batch(arr[1]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  JoinGroupWithStorageResult dco_decode_join_group_with_storage_result(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return JoinGroupWithStorageResult(
      groupId: dco_decode_list_prim_u_8_strict(arr[0]),
      storageBatch: dco_decode_mls_storage_batch(arr[1]),
    );
  }

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_prim_u_8_strict).toList();
  }

  @protected
  List<MlsCiphersuite> dco_decode_list_mls_ciphersuite(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_mls_ciphersuite).toList();
  }

  @protected
  List<MlsStorageEntry> dco_decode_list_mls_storage_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_mls_storage_entry).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MlsCiphersuite dco_decode_mls_ciphersuite(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MlsCiphersuite.values[raw as int];
  }

  @protected
  MlsGroupConfig dco_decode_mls_group_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return MlsGroupConfig(
      ciphersuite: dco_decode_mls_ciphersuite(arr[0]),
      wireFormatPolicy: dco_decode_mls_wire_format_policy(arr[1]),
      useRatchetTreeExtension: dco_decode_bool(arr[2]),
      maxPastEpochs: dco_decode_u_32(arr[3]),
      paddingSize: dco_decode_u_32(arr[4]),
      senderRatchetMaxOutOfOrder: dco_decode_u_32(arr[5]),
      senderRatchetMaxForwardDistance: dco_decode_u_32(arr[6]),
      numberOfResumptionPsks: dco_decode_u_32(arr[7]),
    );
  }

  @protected
  MlsProposalType dco_decode_mls_proposal_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MlsProposalType.values[raw as int];
  }

  @protected
  MlsStorageBatch dco_decode_mls_storage_batch(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return MlsStorageBatch(
      upserts: dco_decode_list_mls_storage_entry(arr[0]),
      deletes: dco_decode_list_list_prim_u_8_strict(arr[1]),
      deletedGroupIds: dco_decode_list_list_prim_u_8_strict(arr[2]),
      storageFormatVersion: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  MlsStorageEntry dco_decode_mls_storage_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return MlsStorageEntry(
      key: dco_decode_list_prim_u_8_strict(arr[0]),
      value: dco_decode_list_prim_u_8_strict(arr[1]),
      groupId: dco_decode_opt_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  MlsWireFormatPolicy dco_decode_mls_wire_format_policy(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MlsWireFormatPolicy.values[raw as int];
  }

  @protected
  MlsProposalType? dco_decode_opt_box_autoadd_mls_proposal_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_mls_proposal_type(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  ProcessMessageWithStorageResult
  dco_decode_process_message_with_storage_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return ProcessMessageWithStorageResult(
      messageType: dco_decode_processed_message_type(arr[0]),
      senderIndex: dco_decode_opt_box_autoadd_u_32(arr[1]),
      previousEpoch: dco_decode_u_64(arr[2]),
      resultingEpoch: dco_decode_u_64(arr[3]),
      applicationMessage: dco_decode_opt_list_prim_u_8_strict(arr[4]),
      hasStagedCommit: dco_decode_bool(arr[5]),
      hasProposal: dco_decode_bool(arr[6]),
      proposalType: dco_decode_opt_box_autoadd_mls_proposal_type(arr[7]),
      storageBatch: dco_decode_mls_storage_batch(arr[8]),
    );
  }

  @protected
  ProcessedMessageType dco_decode_processed_message_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ProcessedMessageType.values[raw as int];
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  MlsCredential
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MlsCredentialImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  MlsSignatureKeyPair
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MlsSignatureKeyPairImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  MlsCredential
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MlsCredentialImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  MlsSignatureKeyPair
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MlsSignatureKeyPairImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  MlsCredential
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MlsCredentialImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  MlsSignatureKeyPair
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MlsSignatureKeyPairImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AddMembersWithStorageResult sse_decode_add_members_with_storage_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_commit = sse_decode_list_prim_u_8_strict(deserializer);
    var var_welcome = sse_decode_list_prim_u_8_strict(deserializer);
    var var_groupInfo = sse_decode_opt_list_prim_u_8_strict(deserializer);
    var var_storageBatch = sse_decode_mls_storage_batch(deserializer);
    return AddMembersWithStorageResult(
      commit: var_commit,
      welcome: var_welcome,
      groupInfo: var_groupInfo,
      storageBatch: var_storageBatch,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  MlsGroupConfig sse_decode_box_autoadd_mls_group_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_mls_group_config(deserializer));
  }

  @protected
  MlsProposalType sse_decode_box_autoadd_mls_proposal_type(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_mls_proposal_type(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  CreateGroupWithStorageResult sse_decode_create_group_with_storage_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_groupId = sse_decode_list_prim_u_8_strict(deserializer);
    var var_storageBatch = sse_decode_mls_storage_batch(deserializer);
    return CreateGroupWithStorageResult(
      groupId: var_groupId,
      storageBatch: var_storageBatch,
    );
  }

  @protected
  CreateKeyPackageWithStorageResult
  sse_decode_create_key_package_with_storage_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_keyPackageBytes = sse_decode_list_prim_u_8_strict(deserializer);
    var var_storageBatch = sse_decode_mls_storage_batch(deserializer);
    return CreateKeyPackageWithStorageResult(
      keyPackageBytes: var_keyPackageBytes,
      storageBatch: var_storageBatch,
    );
  }

  @protected
  CreateMessageWithStorageResult sse_decode_create_message_with_storage_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ciphertext = sse_decode_list_prim_u_8_strict(deserializer);
    var var_storageBatch = sse_decode_mls_storage_batch(deserializer);
    return CreateMessageWithStorageResult(
      ciphertext: var_ciphertext,
      storageBatch: var_storageBatch,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  JoinGroupWithStorageResult sse_decode_join_group_with_storage_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_groupId = sse_decode_list_prim_u_8_strict(deserializer);
    var var_storageBatch = sse_decode_mls_storage_batch(deserializer);
    return JoinGroupWithStorageResult(
      groupId: var_groupId,
      storageBatch: var_storageBatch,
    );
  }

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint8List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_8_strict(deserializer));
    }
    return ans_;
  }

  @protected
  List<MlsCiphersuite> sse_decode_list_mls_ciphersuite(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MlsCiphersuite>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_mls_ciphersuite(deserializer));
    }
    return ans_;
  }

  @protected
  List<MlsStorageEntry> sse_decode_list_mls_storage_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MlsStorageEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_mls_storage_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MlsCiphersuite sse_decode_mls_ciphersuite(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MlsCiphersuite.values[inner];
  }

  @protected
  MlsGroupConfig sse_decode_mls_group_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ciphersuite = sse_decode_mls_ciphersuite(deserializer);
    var var_wireFormatPolicy = sse_decode_mls_wire_format_policy(deserializer);
    var var_useRatchetTreeExtension = sse_decode_bool(deserializer);
    var var_maxPastEpochs = sse_decode_u_32(deserializer);
    var var_paddingSize = sse_decode_u_32(deserializer);
    var var_senderRatchetMaxOutOfOrder = sse_decode_u_32(deserializer);
    var var_senderRatchetMaxForwardDistance = sse_decode_u_32(deserializer);
    var var_numberOfResumptionPsks = sse_decode_u_32(deserializer);
    return MlsGroupConfig(
      ciphersuite: var_ciphersuite,
      wireFormatPolicy: var_wireFormatPolicy,
      useRatchetTreeExtension: var_useRatchetTreeExtension,
      maxPastEpochs: var_maxPastEpochs,
      paddingSize: var_paddingSize,
      senderRatchetMaxOutOfOrder: var_senderRatchetMaxOutOfOrder,
      senderRatchetMaxForwardDistance: var_senderRatchetMaxForwardDistance,
      numberOfResumptionPsks: var_numberOfResumptionPsks,
    );
  }

  @protected
  MlsProposalType sse_decode_mls_proposal_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MlsProposalType.values[inner];
  }

  @protected
  MlsStorageBatch sse_decode_mls_storage_batch(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_upserts = sse_decode_list_mls_storage_entry(deserializer);
    var var_deletes = sse_decode_list_list_prim_u_8_strict(deserializer);
    var var_deletedGroupIds = sse_decode_list_list_prim_u_8_strict(
      deserializer,
    );
    var var_storageFormatVersion = sse_decode_u_32(deserializer);
    return MlsStorageBatch(
      upserts: var_upserts,
      deletes: var_deletes,
      deletedGroupIds: var_deletedGroupIds,
      storageFormatVersion: var_storageFormatVersion,
    );
  }

  @protected
  MlsStorageEntry sse_decode_mls_storage_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_key = sse_decode_list_prim_u_8_strict(deserializer);
    var var_value = sse_decode_list_prim_u_8_strict(deserializer);
    var var_groupId = sse_decode_opt_list_prim_u_8_strict(deserializer);
    return MlsStorageEntry(
      key: var_key,
      value: var_value,
      groupId: var_groupId,
    );
  }

  @protected
  MlsWireFormatPolicy sse_decode_mls_wire_format_policy(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MlsWireFormatPolicy.values[inner];
  }

  @protected
  MlsProposalType? sse_decode_opt_box_autoadd_mls_proposal_type(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_mls_proposal_type(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProcessMessageWithStorageResult
  sse_decode_process_message_with_storage_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_messageType = sse_decode_processed_message_type(deserializer);
    var var_senderIndex = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_previousEpoch = sse_decode_u_64(deserializer);
    var var_resultingEpoch = sse_decode_u_64(deserializer);
    var var_applicationMessage = sse_decode_opt_list_prim_u_8_strict(
      deserializer,
    );
    var var_hasStagedCommit = sse_decode_bool(deserializer);
    var var_hasProposal = sse_decode_bool(deserializer);
    var var_proposalType = sse_decode_opt_box_autoadd_mls_proposal_type(
      deserializer,
    );
    var var_storageBatch = sse_decode_mls_storage_batch(deserializer);
    return ProcessMessageWithStorageResult(
      messageType: var_messageType,
      senderIndex: var_senderIndex,
      previousEpoch: var_previousEpoch,
      resultingEpoch: var_resultingEpoch,
      applicationMessage: var_applicationMessage,
      hasStagedCommit: var_hasStagedCommit,
      hasProposal: var_hasProposal,
      proposalType: var_proposalType,
      storageBatch: var_storageBatch,
    );
  }

  @protected
  ProcessedMessageType sse_decode_processed_message_type(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ProcessedMessageType.values[inner];
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    MlsCredential raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    // ignore: invalid_use_of_internal_member
    return (raw as MlsCredentialImpl).frbInternalCstEncode(move: true);
  }

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    MlsSignatureKeyPair raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    // ignore: invalid_use_of_internal_member
    return (raw as MlsSignatureKeyPairImpl).frbInternalCstEncode(move: true);
  }

  @protected
  int
  cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    MlsCredential raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    // ignore: invalid_use_of_internal_member
    return (raw as MlsCredentialImpl).frbInternalCstEncode(move: false);
  }

  @protected
  int
  cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    MlsSignatureKeyPair raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    // ignore: invalid_use_of_internal_member
    return (raw as MlsSignatureKeyPairImpl).frbInternalCstEncode(move: false);
  }

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    MlsCredential raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    // ignore: invalid_use_of_internal_member
    return (raw as MlsCredentialImpl).frbInternalCstEncode();
  }

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    MlsSignatureKeyPair raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    // ignore: invalid_use_of_internal_member
    return (raw as MlsSignatureKeyPairImpl).frbInternalCstEncode();
  }

  @protected
  bool cst_encode_bool(bool raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_i_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_mls_ciphersuite(MlsCiphersuite raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  int cst_encode_mls_proposal_type(MlsProposalType raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  int cst_encode_mls_wire_format_policy(MlsWireFormatPolicy raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  int cst_encode_processed_message_type(ProcessedMessageType raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  int cst_encode_u_16(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_u_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_u_8(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void cst_encode_unit(void raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    MlsCredential self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MlsCredentialImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    MlsSignatureKeyPair self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MlsSignatureKeyPairImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    MlsCredential self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MlsCredentialImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    MlsSignatureKeyPair self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MlsSignatureKeyPairImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    MlsCredential self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MlsCredentialImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    MlsSignatureKeyPair self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MlsSignatureKeyPairImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_add_members_with_storage_result(
    AddMembersWithStorageResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.commit, serializer);
    sse_encode_list_prim_u_8_strict(self.welcome, serializer);
    sse_encode_opt_list_prim_u_8_strict(self.groupInfo, serializer);
    sse_encode_mls_storage_batch(self.storageBatch, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_mls_group_config(
    MlsGroupConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_mls_group_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_mls_proposal_type(
    MlsProposalType self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_mls_proposal_type(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_create_group_with_storage_result(
    CreateGroupWithStorageResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.groupId, serializer);
    sse_encode_mls_storage_batch(self.storageBatch, serializer);
  }

  @protected
  void sse_encode_create_key_package_with_storage_result(
    CreateKeyPackageWithStorageResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.keyPackageBytes, serializer);
    sse_encode_mls_storage_batch(self.storageBatch, serializer);
  }

  @protected
  void sse_encode_create_message_with_storage_result(
    CreateMessageWithStorageResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.ciphertext, serializer);
    sse_encode_mls_storage_batch(self.storageBatch, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_join_group_with_storage_result(
    JoinGroupWithStorageResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.groupId, serializer);
    sse_encode_mls_storage_batch(self.storageBatch, serializer);
  }

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_u_8_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_mls_ciphersuite(
    List<MlsCiphersuite> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_mls_ciphersuite(item, serializer);
    }
  }

  @protected
  void sse_encode_list_mls_storage_entry(
    List<MlsStorageEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_mls_storage_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_mls_ciphersuite(
    MlsCiphersuite self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_mls_group_config(
    MlsGroupConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_mls_ciphersuite(self.ciphersuite, serializer);
    sse_encode_mls_wire_format_policy(self.wireFormatPolicy, serializer);
    sse_encode_bool(self.useRatchetTreeExtension, serializer);
    sse_encode_u_32(self.maxPastEpochs, serializer);
    sse_encode_u_32(self.paddingSize, serializer);
    sse_encode_u_32(self.senderRatchetMaxOutOfOrder, serializer);
    sse_encode_u_32(self.senderRatchetMaxForwardDistance, serializer);
    sse_encode_u_32(self.numberOfResumptionPsks, serializer);
  }

  @protected
  void sse_encode_mls_proposal_type(
    MlsProposalType self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_mls_storage_batch(
    MlsStorageBatch self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_mls_storage_entry(self.upserts, serializer);
    sse_encode_list_list_prim_u_8_strict(self.deletes, serializer);
    sse_encode_list_list_prim_u_8_strict(self.deletedGroupIds, serializer);
    sse_encode_u_32(self.storageFormatVersion, serializer);
  }

  @protected
  void sse_encode_mls_storage_entry(
    MlsStorageEntry self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.key, serializer);
    sse_encode_list_prim_u_8_strict(self.value, serializer);
    sse_encode_opt_list_prim_u_8_strict(self.groupId, serializer);
  }

  @protected
  void sse_encode_mls_wire_format_policy(
    MlsWireFormatPolicy self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_opt_box_autoadd_mls_proposal_type(
    MlsProposalType? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_mls_proposal_type(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_process_message_with_storage_result(
    ProcessMessageWithStorageResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_processed_message_type(self.messageType, serializer);
    sse_encode_opt_box_autoadd_u_32(self.senderIndex, serializer);
    sse_encode_u_64(self.previousEpoch, serializer);
    sse_encode_u_64(self.resultingEpoch, serializer);
    sse_encode_opt_list_prim_u_8_strict(self.applicationMessage, serializer);
    sse_encode_bool(self.hasStagedCommit, serializer);
    sse_encode_bool(self.hasProposal, serializer);
    sse_encode_opt_box_autoadd_mls_proposal_type(self.proposalType, serializer);
    sse_encode_mls_storage_batch(self.storageBatch, serializer);
  }

  @protected
  void sse_encode_processed_message_type(
    ProcessedMessageType self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class MlsCredentialImpl extends RustOpaque implements MlsCredential {
  // Not to be used by end users
  MlsCredentialImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  MlsCredentialImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_MlsCredential,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_MlsCredential,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_MlsCredentialPtr,
  );

  /// Returns the certificate chain from an X.509 credential.
  ///
  /// Each entry is a DER-encoded X.509 certificate.
  /// Returns an error if this is not an X.509 credential.
  List<Uint8List> certificates() => RustLib.instance.api
      .crateApiCredentialMlsCredentialCertificates(that: this);

  /// Returns the credential type value (1 = Basic, 2 = X509).
  int credentialType() => RustLib.instance.api
      .crateApiCredentialMlsCredentialCredentialType(that: this);

  /// Returns the identity bytes from a BasicCredential.
  ///
  /// Returns an error if this is not a BasicCredential.
  Uint8List identity() =>
      RustLib.instance.api.crateApiCredentialMlsCredentialIdentity(that: this);

  /// TLS-serialize this credential for wire transmission.
  Uint8List serialize() =>
      RustLib.instance.api.crateApiCredentialMlsCredentialSerialize(that: this);

  /// Returns the raw serialized content of this credential.
  ///
  /// For BasicCredential, this is the identity bytes.
  /// For X.509, this is the TLS-serialized certificate chain.
  Uint8List serializedContent() => RustLib.instance.api
      .crateApiCredentialMlsCredentialSerializedContent(that: this);
}

@sealed
class MlsSignatureKeyPairImpl extends RustOpaque
    implements MlsSignatureKeyPair {
  // Not to be used by end users
  MlsSignatureKeyPairImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  MlsSignatureKeyPairImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_increment_strong_count_MlsSignatureKeyPair,
    rustArcDecrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_MlsSignatureKeyPair,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_MlsSignatureKeyPairPtr,
  );

  /// Returns the private key bytes.
  ///
  /// # Security
  /// The returned bytes contain private key material. The caller is responsible
  /// for securely zeroing these bytes when done.
  Uint8List privateKey() => RustLib.instance.api
      .crateApiKeysMlsSignatureKeyPairPrivateKey(that: this);

  /// Returns the public key bytes.
  Uint8List publicKey() =>
      RustLib.instance.api.crateApiKeysMlsSignatureKeyPairPublicKey(that: this);

  /// Serialize the key pair to bytes for storage.
  ///
  /// The returned bytes contain the **public key and signature scheme only** —
  /// no private key material. To reconstruct a full key pair with private key,
  /// use `from_raw()` with the original private key bytes.
  Uint8List serialize() =>
      RustLib.instance.api.crateApiKeysMlsSignatureKeyPairSerialize(that: this);

  /// Returns the signature scheme as a u16.
  int signatureScheme() => RustLib.instance.api
      .crateApiKeysMlsSignatureKeyPairSignatureScheme(that: this);
}
