// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/config.dart';
import 'api/credential.dart';
import 'api/group_e2ee.dart';
import 'api/init.dart';
import 'api/keys.dart';
import 'api/message.dart';
import 'api/storage.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_MlsCredentialPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_MlsSignatureKeyPairPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair;

  @protected
  MlsCredential
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    dynamic raw,
  );

  @protected
  MlsSignatureKeyPair
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    dynamic raw,
  );

  @protected
  MlsCredential
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    dynamic raw,
  );

  @protected
  MlsSignatureKeyPair
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    dynamic raw,
  );

  @protected
  MlsCredential
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    dynamic raw,
  );

  @protected
  MlsSignatureKeyPair
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  MlsAuthorizedOwnerV1 dco_decode_box_autoadd_mls_authorized_owner_v_1(
    dynamic raw,
  );

  @protected
  MlsAuthorizedSelfV1 dco_decode_box_autoadd_mls_authorized_self_v_1(
    dynamic raw,
  );

  @protected
  MlsExpectedRosterStateV1 dco_decode_box_autoadd_mls_expected_roster_state_v_1(
    dynamic raw,
  );

  @protected
  MlsGroupConfig dco_decode_box_autoadd_mls_group_config(dynamic raw);

  @protected
  MlsProposalType dco_decode_box_autoadd_mls_proposal_type(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  CreateGroupWithStorageResult dco_decode_create_group_with_storage_result(
    dynamic raw,
  );

  @protected
  CreateKeyPackageWithStorageResult
  dco_decode_create_key_package_with_storage_result(dynamic raw);

  @protected
  CreateMessageWithStorageResult dco_decode_create_message_with_storage_result(
    dynamic raw,
  );

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  JoinGroupWithStorageResult dco_decode_join_group_with_storage_result(
    dynamic raw,
  );

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

  @protected
  List<MlsAuthorizedKeyPackageV1>
  dco_decode_list_mls_authorized_key_package_v_1(dynamic raw);

  @protected
  List<MlsAuthorizedRemovalV1> dco_decode_list_mls_authorized_removal_v_1(
    dynamic raw,
  );

  @protected
  List<MlsCiphersuite> dco_decode_list_mls_ciphersuite(dynamic raw);

  @protected
  List<MlsRosterLeafV1> dco_decode_list_mls_roster_leaf_v_1(dynamic raw);

  @protected
  List<MlsStorageEntry> dco_decode_list_mls_storage_entry(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MlsAuthorizedKeyPackageV1 dco_decode_mls_authorized_key_package_v_1(
    dynamic raw,
  );

  @protected
  MlsAuthorizedOwnerV1 dco_decode_mls_authorized_owner_v_1(dynamic raw);

  @protected
  MlsAuthorizedRemovalV1 dco_decode_mls_authorized_removal_v_1(dynamic raw);

  @protected
  MlsAuthorizedSelfV1 dco_decode_mls_authorized_self_v_1(dynamic raw);

  @protected
  MlsCiphersuite dco_decode_mls_ciphersuite(dynamic raw);

  @protected
  MlsExpectedRosterStateV1 dco_decode_mls_expected_roster_state_v_1(
    dynamic raw,
  );

  @protected
  MlsGroupConfig dco_decode_mls_group_config(dynamic raw);

  @protected
  MlsProposalType dco_decode_mls_proposal_type(dynamic raw);

  @protected
  MlsRosterLeafV1 dco_decode_mls_roster_leaf_v_1(dynamic raw);

  @protected
  MlsRosterSummaryV1 dco_decode_mls_roster_summary_v_1(dynamic raw);

  @protected
  MlsStorageBatch dco_decode_mls_storage_batch(dynamic raw);

  @protected
  MlsStorageEntry dco_decode_mls_storage_entry(dynamic raw);

  @protected
  MlsWireFormatPolicy dco_decode_mls_wire_format_policy(dynamic raw);

  @protected
  MlsProposalType? dco_decode_opt_box_autoadd_mls_proposal_type(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  PreparedCommitWithStorageResult
  dco_decode_prepared_commit_with_storage_result(dynamic raw);

  @protected
  ProcessMessageWithStorageResult
  dco_decode_process_message_with_storage_result(dynamic raw);

  @protected
  ProcessedMessageType dco_decode_processed_message_type(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  MlsCredential
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    SseDeserializer deserializer,
  );

  @protected
  MlsSignatureKeyPair
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    SseDeserializer deserializer,
  );

  @protected
  MlsCredential
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    SseDeserializer deserializer,
  );

  @protected
  MlsSignatureKeyPair
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    SseDeserializer deserializer,
  );

  @protected
  MlsCredential
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    SseDeserializer deserializer,
  );

  @protected
  MlsSignatureKeyPair
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  MlsAuthorizedOwnerV1 sse_decode_box_autoadd_mls_authorized_owner_v_1(
    SseDeserializer deserializer,
  );

  @protected
  MlsAuthorizedSelfV1 sse_decode_box_autoadd_mls_authorized_self_v_1(
    SseDeserializer deserializer,
  );

  @protected
  MlsExpectedRosterStateV1 sse_decode_box_autoadd_mls_expected_roster_state_v_1(
    SseDeserializer deserializer,
  );

  @protected
  MlsGroupConfig sse_decode_box_autoadd_mls_group_config(
    SseDeserializer deserializer,
  );

  @protected
  MlsProposalType sse_decode_box_autoadd_mls_proposal_type(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  CreateGroupWithStorageResult sse_decode_create_group_with_storage_result(
    SseDeserializer deserializer,
  );

  @protected
  CreateKeyPackageWithStorageResult
  sse_decode_create_key_package_with_storage_result(
    SseDeserializer deserializer,
  );

  @protected
  CreateMessageWithStorageResult sse_decode_create_message_with_storage_result(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  JoinGroupWithStorageResult sse_decode_join_group_with_storage_result(
    SseDeserializer deserializer,
  );

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  );

  @protected
  List<MlsAuthorizedKeyPackageV1>
  sse_decode_list_mls_authorized_key_package_v_1(SseDeserializer deserializer);

  @protected
  List<MlsAuthorizedRemovalV1> sse_decode_list_mls_authorized_removal_v_1(
    SseDeserializer deserializer,
  );

  @protected
  List<MlsCiphersuite> sse_decode_list_mls_ciphersuite(
    SseDeserializer deserializer,
  );

  @protected
  List<MlsRosterLeafV1> sse_decode_list_mls_roster_leaf_v_1(
    SseDeserializer deserializer,
  );

  @protected
  List<MlsStorageEntry> sse_decode_list_mls_storage_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MlsAuthorizedKeyPackageV1 sse_decode_mls_authorized_key_package_v_1(
    SseDeserializer deserializer,
  );

  @protected
  MlsAuthorizedOwnerV1 sse_decode_mls_authorized_owner_v_1(
    SseDeserializer deserializer,
  );

  @protected
  MlsAuthorizedRemovalV1 sse_decode_mls_authorized_removal_v_1(
    SseDeserializer deserializer,
  );

  @protected
  MlsAuthorizedSelfV1 sse_decode_mls_authorized_self_v_1(
    SseDeserializer deserializer,
  );

  @protected
  MlsCiphersuite sse_decode_mls_ciphersuite(SseDeserializer deserializer);

  @protected
  MlsExpectedRosterStateV1 sse_decode_mls_expected_roster_state_v_1(
    SseDeserializer deserializer,
  );

  @protected
  MlsGroupConfig sse_decode_mls_group_config(SseDeserializer deserializer);

  @protected
  MlsProposalType sse_decode_mls_proposal_type(SseDeserializer deserializer);

  @protected
  MlsRosterLeafV1 sse_decode_mls_roster_leaf_v_1(SseDeserializer deserializer);

  @protected
  MlsRosterSummaryV1 sse_decode_mls_roster_summary_v_1(
    SseDeserializer deserializer,
  );

  @protected
  MlsStorageBatch sse_decode_mls_storage_batch(SseDeserializer deserializer);

  @protected
  MlsStorageEntry sse_decode_mls_storage_entry(SseDeserializer deserializer);

  @protected
  MlsWireFormatPolicy sse_decode_mls_wire_format_policy(
    SseDeserializer deserializer,
  );

  @protected
  MlsProposalType? sse_decode_opt_box_autoadd_mls_proposal_type(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  PreparedCommitWithStorageResult
  sse_decode_prepared_commit_with_storage_result(SseDeserializer deserializer);

  @protected
  ProcessMessageWithStorageResult
  sse_decode_process_message_with_storage_result(SseDeserializer deserializer);

  @protected
  ProcessedMessageType sse_decode_processed_message_type(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  String cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  JSAny cst_encode_box_autoadd_mls_authorized_owner_v_1(
    MlsAuthorizedOwnerV1 raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_mls_authorized_owner_v_1(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_mls_authorized_self_v_1(
    MlsAuthorizedSelfV1 raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_mls_authorized_self_v_1(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_mls_expected_roster_state_v_1(
    MlsExpectedRosterStateV1 raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_mls_expected_roster_state_v_1(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_mls_group_config(MlsGroupConfig raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_mls_group_config(raw);
  }

  @protected
  int cst_encode_box_autoadd_mls_proposal_type(MlsProposalType raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_mls_proposal_type(raw);
  }

  @protected
  int cst_encode_box_autoadd_u_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_u_32(raw);
  }

  @protected
  JSAny cst_encode_create_group_with_storage_result(
    CreateGroupWithStorageResult raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_list_prim_u_8_strict(raw.groupId),
      cst_encode_mls_roster_summary_v_1(raw.resultingRoster),
      cst_encode_mls_storage_batch(raw.storageBatch),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_create_key_package_with_storage_result(
    CreateKeyPackageWithStorageResult raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_list_prim_u_8_strict(raw.keyPackageBytes),
      cst_encode_mls_storage_batch(raw.storageBatch),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_create_message_with_storage_result(
    CreateMessageWithStorageResult raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_list_prim_u_8_strict(raw.ciphertext),
      cst_encode_mls_storage_batch(raw.storageBatch),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_join_group_with_storage_result(
    JoinGroupWithStorageResult raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_list_prim_u_8_strict(raw.groupId),
      cst_encode_mls_roster_summary_v_1(raw.resultingRoster),
      cst_encode_mls_storage_batch(raw.storageBatch),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_list_list_prim_u_8_strict(List<Uint8List> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_list_prim_u_8_strict).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_mls_authorized_key_package_v_1(
    List<MlsAuthorizedKeyPackageV1> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_mls_authorized_key_package_v_1).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_mls_authorized_removal_v_1(
    List<MlsAuthorizedRemovalV1> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_mls_authorized_removal_v_1).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_mls_ciphersuite(List<MlsCiphersuite> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_mls_ciphersuite).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_mls_roster_leaf_v_1(List<MlsRosterLeafV1> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_mls_roster_leaf_v_1).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_mls_storage_entry(List<MlsStorageEntry> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_mls_storage_entry).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_loose(List<int> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_strict(Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_mls_authorized_key_package_v_1(
    MlsAuthorizedKeyPackageV1 raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_list_prim_u_8_strict(raw.keyPackageBytes),
      cst_encode_list_prim_u_8_strict(raw.expectedCredentialIdentity),
      cst_encode_list_prim_u_8_strict(raw.expectedSignaturePublicKey),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_mls_authorized_owner_v_1(MlsAuthorizedOwnerV1 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_list_prim_u_8_strict(raw.expectedCredentialIdentity),
      cst_encode_list_prim_u_8_strict(raw.expectedSignaturePublicKey),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_mls_authorized_removal_v_1(MlsAuthorizedRemovalV1 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_u_32(raw.leafIndex),
      cst_encode_list_prim_u_8_strict(raw.expectedCredentialIdentity),
      cst_encode_list_prim_u_8_strict(raw.expectedSignaturePublicKey),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_mls_authorized_self_v_1(MlsAuthorizedSelfV1 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_u_32(raw.leafIndex),
      cst_encode_list_prim_u_8_strict(raw.expectedCredentialIdentity),
      cst_encode_list_prim_u_8_strict(raw.expectedSignaturePublicKey),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_mls_expected_roster_state_v_1(MlsExpectedRosterStateV1 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_list_prim_u_8_strict(raw.groupId),
      cst_encode_u_64(raw.epoch),
      cst_encode_list_prim_u_8_strict(raw.digestSha256),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_mls_group_config(MlsGroupConfig raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_mls_ciphersuite(raw.ciphersuite),
      cst_encode_mls_wire_format_policy(raw.wireFormatPolicy),
      cst_encode_bool(raw.useRatchetTreeExtension),
      cst_encode_u_32(raw.maxPastEpochs),
      cst_encode_u_32(raw.paddingSize),
      cst_encode_u_32(raw.senderRatchetMaxOutOfOrder),
      cst_encode_u_32(raw.senderRatchetMaxForwardDistance),
      cst_encode_u_32(raw.numberOfResumptionPsks),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_mls_roster_leaf_v_1(MlsRosterLeafV1 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_u_32(raw.leafIndex),
      cst_encode_list_prim_u_8_strict(raw.credentialIdentity),
      cst_encode_list_prim_u_8_strict(raw.signaturePublicKey),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_mls_roster_summary_v_1(MlsRosterSummaryV1 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_list_prim_u_8_strict(raw.groupId),
      cst_encode_u_64(raw.epoch),
      cst_encode_list_mls_roster_leaf_v_1(raw.leaves),
      cst_encode_list_prim_u_8_strict(raw.digestSha256),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_mls_storage_batch(MlsStorageBatch raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_list_mls_storage_entry(raw.upserts),
      cst_encode_list_list_prim_u_8_strict(raw.deletes),
      cst_encode_list_list_prim_u_8_strict(raw.deletedGroupIds),
      cst_encode_u_32(raw.storageFormatVersion),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_mls_storage_entry(MlsStorageEntry raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_list_prim_u_8_strict(raw.key),
      cst_encode_list_prim_u_8_strict(raw.value),
      cst_encode_opt_list_prim_u_8_strict(raw.groupId),
    ].jsify()!;
  }

  @protected
  int? cst_encode_opt_box_autoadd_mls_proposal_type(MlsProposalType? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_mls_proposal_type(raw);
  }

  @protected
  int? cst_encode_opt_box_autoadd_u_32(int? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_u_32(raw);
  }

  @protected
  JSAny? cst_encode_opt_list_prim_u_8_strict(Uint8List? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_list_prim_u_8_strict(raw);
  }

  @protected
  JSAny cst_encode_prepared_commit_with_storage_result(
    PreparedCommitWithStorageResult raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_list_prim_u_8_strict(raw.commit),
      cst_encode_opt_list_prim_u_8_strict(raw.welcome),
      cst_encode_opt_list_prim_u_8_strict(raw.groupInfo),
      cst_encode_list_prim_u_8_strict(raw.commitSha256),
      cst_encode_mls_roster_summary_v_1(raw.previousRoster),
      cst_encode_mls_roster_summary_v_1(raw.resultingRoster),
      cst_encode_list_prim_u_8_strict(raw.baseGroupStateSha256),
      cst_encode_mls_storage_batch(raw.storageBatch),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_process_message_with_storage_result(
    ProcessMessageWithStorageResult raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_processed_message_type(raw.messageType),
      cst_encode_opt_box_autoadd_u_32(raw.senderIndex),
      cst_encode_u_64(raw.previousEpoch),
      cst_encode_u_64(raw.resultingEpoch),
      cst_encode_opt_list_prim_u_8_strict(raw.applicationMessage),
      cst_encode_bool(raw.hasStagedCommit),
      cst_encode_bool(raw.hasProposal),
      cst_encode_opt_box_autoadd_mls_proposal_type(raw.proposalType),
      cst_encode_mls_roster_summary_v_1(raw.previousRoster),
      cst_encode_mls_roster_summary_v_1(raw.resultingRoster),
      cst_encode_mls_storage_batch(raw.storageBatch),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  JSAny cst_encode_usize(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    MlsCredential raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    MlsSignatureKeyPair raw,
  );

  @protected
  int
  cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    MlsCredential raw,
  );

  @protected
  int
  cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    MlsSignatureKeyPair raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    MlsCredential raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    MlsSignatureKeyPair raw,
  );

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_mls_ciphersuite(MlsCiphersuite raw);

  @protected
  int cst_encode_mls_proposal_type(MlsProposalType raw);

  @protected
  int cst_encode_mls_wire_format_policy(MlsWireFormatPolicy raw);

  @protected
  int cst_encode_processed_message_type(ProcessedMessageType raw);

  @protected
  int cst_encode_u_16(int raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    MlsCredential self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    MlsSignatureKeyPair self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    MlsCredential self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    MlsSignatureKeyPair self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    MlsCredential self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    MlsSignatureKeyPair self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_mls_authorized_owner_v_1(
    MlsAuthorizedOwnerV1 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_mls_authorized_self_v_1(
    MlsAuthorizedSelfV1 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_mls_expected_roster_state_v_1(
    MlsExpectedRosterStateV1 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_mls_group_config(
    MlsGroupConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_mls_proposal_type(
    MlsProposalType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_create_group_with_storage_result(
    CreateGroupWithStorageResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_create_key_package_with_storage_result(
    CreateKeyPackageWithStorageResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_create_message_with_storage_result(
    CreateMessageWithStorageResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_join_group_with_storage_result(
    JoinGroupWithStorageResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_mls_authorized_key_package_v_1(
    List<MlsAuthorizedKeyPackageV1> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_mls_authorized_removal_v_1(
    List<MlsAuthorizedRemovalV1> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_mls_ciphersuite(
    List<MlsCiphersuite> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_mls_roster_leaf_v_1(
    List<MlsRosterLeafV1> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_mls_storage_entry(
    List<MlsStorageEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mls_authorized_key_package_v_1(
    MlsAuthorizedKeyPackageV1 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mls_authorized_owner_v_1(
    MlsAuthorizedOwnerV1 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mls_authorized_removal_v_1(
    MlsAuthorizedRemovalV1 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mls_authorized_self_v_1(
    MlsAuthorizedSelfV1 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mls_ciphersuite(
    MlsCiphersuite self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mls_expected_roster_state_v_1(
    MlsExpectedRosterStateV1 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mls_group_config(
    MlsGroupConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mls_proposal_type(
    MlsProposalType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mls_roster_leaf_v_1(
    MlsRosterLeafV1 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mls_roster_summary_v_1(
    MlsRosterSummaryV1 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mls_storage_batch(
    MlsStorageBatch self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mls_storage_entry(
    MlsStorageEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mls_wire_format_policy(
    MlsWireFormatPolicy self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_mls_proposal_type(
    MlsProposalType? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_prepared_commit_with_storage_result(
    PreparedCommitWithStorageResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_process_message_with_storage_result(
    ProcessMessageWithStorageResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_processed_message_type(
    ProcessedMessageType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__credential__MlsCredential_basic(JSAny identity) =>
      wasmModule.wire__crate__api__credential__MlsCredential_basic(identity);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__credential__MlsCredential_certificates(int that) =>
      wasmModule.wire__crate__api__credential__MlsCredential_certificates(that);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__credential__MlsCredential_credential_type(int that) =>
      wasmModule.wire__crate__api__credential__MlsCredential_credential_type(
        that,
      );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__credential__MlsCredential_deserialize(JSAny bytes) =>
      wasmModule.wire__crate__api__credential__MlsCredential_deserialize(bytes);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__credential__MlsCredential_identity(int that) =>
      wasmModule.wire__crate__api__credential__MlsCredential_identity(that);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__credential__MlsCredential_serialize(int that) =>
      wasmModule.wire__crate__api__credential__MlsCredential_serialize(that);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__credential__MlsCredential_serialized_content(int that) =>
      wasmModule.wire__crate__api__credential__MlsCredential_serialized_content(
        that,
      );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__credential__MlsCredential_x509(JSAny certificate_chain) =>
      wasmModule.wire__crate__api__credential__MlsCredential_x509(
        certificate_chain,
      );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__keys__MlsSignatureKeyPair_deserialize_public(JSAny bytes) =>
      wasmModule.wire__crate__api__keys__MlsSignatureKeyPair_deserialize_public(
        bytes,
      );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__keys__MlsSignatureKeyPair_from_raw(
    int ciphersuite,
    JSAny private_key,
    JSAny public_key,
  ) => wasmModule.wire__crate__api__keys__MlsSignatureKeyPair_from_raw(
    ciphersuite,
    private_key,
    public_key,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__keys__MlsSignatureKeyPair_generate(int ciphersuite) =>
      wasmModule.wire__crate__api__keys__MlsSignatureKeyPair_generate(
        ciphersuite,
      );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__keys__MlsSignatureKeyPair_private_key(int that) =>
      wasmModule.wire__crate__api__keys__MlsSignatureKeyPair_private_key(that);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__keys__MlsSignatureKeyPair_public_key(int that) =>
      wasmModule.wire__crate__api__keys__MlsSignatureKeyPair_public_key(that);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__keys__MlsSignatureKeyPair_serialize(int that) =>
      wasmModule.wire__crate__api__keys__MlsSignatureKeyPair_serialize(that);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__keys__MlsSignatureKeyPair_signature_scheme(int that) =>
      wasmModule.wire__crate__api__keys__MlsSignatureKeyPair_signature_scheme(
        that,
      );

  void wire__crate__api__group_e2ee__add_members_with_storage(
    NativePortType port_,
    JSAny group_id,
    JSAny signer_bytes,
    JSAny additions,
    JSAny aad,
    JSAny expected_previous_state,
    JSAny storage_entries,
    int storage_format_version,
  ) => wasmModule.wire__crate__api__group_e2ee__add_members_with_storage(
    port_,
    group_id,
    signer_bytes,
    additions,
    aad,
    expected_previous_state,
    storage_entries,
    storage_format_version,
  );

  void wire__crate__api__group_e2ee__create_group_with_storage(
    NativePortType port_,
    JSAny config,
    JSAny signer_bytes,
    JSAny explicit_group_id,
    JSAny expected_owner_authority,
    JSAny? credential_bytes,
    JSAny storage_entries,
    int storage_format_version,
  ) => wasmModule.wire__crate__api__group_e2ee__create_group_with_storage(
    port_,
    config,
    signer_bytes,
    explicit_group_id,
    expected_owner_authority,
    credential_bytes,
    storage_entries,
    storage_format_version,
  );

  void wire__crate__api__storage__create_key_package_with_storage(
    NativePortType port_,
    int ciphersuite,
    JSAny signer_bytes,
    JSAny credential_identity,
    JSAny signer_public_key,
    JSAny? credential_bytes,
    JSAny storage_entries,
    int storage_format_version,
  ) => wasmModule.wire__crate__api__storage__create_key_package_with_storage(
    port_,
    ciphersuite,
    signer_bytes,
    credential_identity,
    signer_public_key,
    credential_bytes,
    storage_entries,
    storage_format_version,
  );

  void wire__crate__api__storage__create_message_with_storage(
    NativePortType port_,
    JSAny group_id,
    JSAny signer_bytes,
    JSAny message,
    JSAny aad,
    JSAny storage_entries,
    int storage_format_version,
  ) => wasmModule.wire__crate__api__storage__create_message_with_storage(
    port_,
    group_id,
    signer_bytes,
    message,
    aad,
    storage_entries,
    storage_format_version,
  );

  void wire__crate__api__storage__delete_group_with_storage(
    NativePortType port_,
    JSAny group_id,
    JSAny storage_entries,
    int storage_format_version,
  ) => wasmModule.wire__crate__api__storage__delete_group_with_storage(
    port_,
    group_id,
    storage_entries,
    storage_format_version,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__init__init_openmls(String _library_path) =>
      wasmModule.wire__crate__api__init__init_openmls(_library_path);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__init__is_openmls_initialized() =>
      wasmModule.wire__crate__api__init__is_openmls_initialized();

  void wire__crate__api__group_e2ee__join_group_from_welcome_with_storage(
    NativePortType port_,
    JSAny config,
    JSAny welcome_bytes,
    JSAny? ratchet_tree_bytes,
    JSAny signer_bytes,
    JSAny expected_resulting_state,
    JSAny storage_entries,
    int storage_format_version,
  ) => wasmModule
      .wire__crate__api__group_e2ee__join_group_from_welcome_with_storage(
        port_,
        config,
        welcome_bytes,
        ratchet_tree_bytes,
        signer_bytes,
        expected_resulting_state,
        storage_entries,
        storage_format_version,
      );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__config__mls_group_config_default_config(int ciphersuite) =>
      wasmModule.wire__crate__api__config__mls_group_config_default_config(
        ciphersuite,
      );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__group_e2ee__mls_group_state_digest(
    JSAny group_id,
    JSAny storage_entries,
    int storage_format_version,
  ) => wasmModule.wire__crate__api__group_e2ee__mls_group_state_digest(
    group_id,
    storage_entries,
    storage_format_version,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__message__mls_message_content_type(JSAny message_bytes) =>
      wasmModule.wire__crate__api__message__mls_message_content_type(
        message_bytes,
      );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__message__mls_message_extract_epoch(JSAny message_bytes) =>
      wasmModule.wire__crate__api__message__mls_message_extract_epoch(
        message_bytes,
      );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__message__mls_message_extract_group_id(
    JSAny message_bytes,
  ) => wasmModule.wire__crate__api__message__mls_message_extract_group_id(
    message_bytes,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__group_e2ee__mls_roster_digest_v1(
    JSAny group_id,
    JSAny epoch,
    JSAny leaves,
  ) => wasmModule.wire__crate__api__group_e2ee__mls_roster_digest_v1(
    group_id,
    epoch,
    leaves,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__storage__mls_storage_format_version() =>
      wasmModule.wire__crate__api__storage__mls_storage_format_version();

  void wire__crate__api__group_e2ee__process_message_with_storage(
    NativePortType port_,
    JSAny group_id,
    JSAny message_bytes,
    JSAny expected_aad,
    JSAny expected_previous_state,
    JSAny expected_resulting_state,
    JSAny storage_entries,
    int storage_format_version,
  ) => wasmModule.wire__crate__api__group_e2ee__process_message_with_storage(
    port_,
    group_id,
    message_bytes,
    expected_aad,
    expected_previous_state,
    expected_resulting_state,
    storage_entries,
    storage_format_version,
  );

  void wire__crate__api__group_e2ee__remove_members_with_storage(
    NativePortType port_,
    JSAny group_id,
    JSAny signer_bytes,
    JSAny removals,
    JSAny aad,
    JSAny expected_previous_state,
    JSAny storage_entries,
    int storage_format_version,
  ) => wasmModule.wire__crate__api__group_e2ee__remove_members_with_storage(
    port_,
    group_id,
    signer_bytes,
    removals,
    aad,
    expected_previous_state,
    storage_entries,
    storage_format_version,
  );

  void wire__crate__api__group_e2ee__self_update_with_storage(
    NativePortType port_,
    JSAny group_id,
    JSAny signer_bytes,
    JSAny aad,
    JSAny expected_previous_state,
    JSAny expected_self_authority,
    JSAny storage_entries,
    int storage_format_version,
  ) => wasmModule.wire__crate__api__group_e2ee__self_update_with_storage(
    port_,
    group_id,
    signer_bytes,
    aad,
    expected_previous_state,
    expected_self_authority,
    storage_entries,
    storage_format_version,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__keys__serialize_signer(
    int ciphersuite,
    JSAny private_key,
    JSAny public_key,
  ) => wasmModule.wire__crate__api__keys__serialize_signer(
    ciphersuite,
    private_key,
    public_key,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__types__supported_ciphersuites() =>
      wasmModule.wire__crate__api__types__supported_ciphersuites();

  void wire__crate__api__group_e2ee__swap_members_with_storage(
    NativePortType port_,
    JSAny group_id,
    JSAny signer_bytes,
    JSAny removals,
    JSAny additions,
    JSAny aad,
    JSAny expected_previous_state,
    JSAny storage_entries,
    int storage_format_version,
  ) => wasmModule.wire__crate__api__group_e2ee__swap_members_with_storage(
    port_,
    group_id,
    signer_bytes,
    removals,
    additions,
    aad,
    expected_previous_state,
    storage_entries,
    storage_format_version,
  );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__credential__MlsCredential_basic(JSAny identity);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__credential__MlsCredential_certificates(int that);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__credential__MlsCredential_credential_type(int that);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__credential__MlsCredential_deserialize(JSAny bytes);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__credential__MlsCredential_identity(int that);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__credential__MlsCredential_serialize(int that);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__credential__MlsCredential_serialized_content(int that);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__credential__MlsCredential_x509(JSAny certificate_chain);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__keys__MlsSignatureKeyPair_deserialize_public(JSAny bytes);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__keys__MlsSignatureKeyPair_from_raw(
    int ciphersuite,
    JSAny private_key,
    JSAny public_key,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__keys__MlsSignatureKeyPair_generate(int ciphersuite);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__keys__MlsSignatureKeyPair_private_key(int that);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__keys__MlsSignatureKeyPair_public_key(int that);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__keys__MlsSignatureKeyPair_serialize(int that);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__keys__MlsSignatureKeyPair_signature_scheme(int that);

  external void wire__crate__api__group_e2ee__add_members_with_storage(
    NativePortType port_,
    JSAny group_id,
    JSAny signer_bytes,
    JSAny additions,
    JSAny aad,
    JSAny expected_previous_state,
    JSAny storage_entries,
    int storage_format_version,
  );

  external void wire__crate__api__group_e2ee__create_group_with_storage(
    NativePortType port_,
    JSAny config,
    JSAny signer_bytes,
    JSAny explicit_group_id,
    JSAny expected_owner_authority,
    JSAny? credential_bytes,
    JSAny storage_entries,
    int storage_format_version,
  );

  external void wire__crate__api__storage__create_key_package_with_storage(
    NativePortType port_,
    int ciphersuite,
    JSAny signer_bytes,
    JSAny credential_identity,
    JSAny signer_public_key,
    JSAny? credential_bytes,
    JSAny storage_entries,
    int storage_format_version,
  );

  external void wire__crate__api__storage__create_message_with_storage(
    NativePortType port_,
    JSAny group_id,
    JSAny signer_bytes,
    JSAny message,
    JSAny aad,
    JSAny storage_entries,
    int storage_format_version,
  );

  external void wire__crate__api__storage__delete_group_with_storage(
    NativePortType port_,
    JSAny group_id,
    JSAny storage_entries,
    int storage_format_version,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__init__init_openmls(String _library_path);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__init__is_openmls_initialized();

  external void
  wire__crate__api__group_e2ee__join_group_from_welcome_with_storage(
    NativePortType port_,
    JSAny config,
    JSAny welcome_bytes,
    JSAny? ratchet_tree_bytes,
    JSAny signer_bytes,
    JSAny expected_resulting_state,
    JSAny storage_entries,
    int storage_format_version,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__config__mls_group_config_default_config(int ciphersuite);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__group_e2ee__mls_group_state_digest(
    JSAny group_id,
    JSAny storage_entries,
    int storage_format_version,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__message__mls_message_content_type(JSAny message_bytes);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__message__mls_message_extract_epoch(JSAny message_bytes);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__message__mls_message_extract_group_id(JSAny message_bytes);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__group_e2ee__mls_roster_digest_v1(
    JSAny group_id,
    JSAny epoch,
    JSAny leaves,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__storage__mls_storage_format_version();

  external void wire__crate__api__group_e2ee__process_message_with_storage(
    NativePortType port_,
    JSAny group_id,
    JSAny message_bytes,
    JSAny expected_aad,
    JSAny expected_previous_state,
    JSAny expected_resulting_state,
    JSAny storage_entries,
    int storage_format_version,
  );

  external void wire__crate__api__group_e2ee__remove_members_with_storage(
    NativePortType port_,
    JSAny group_id,
    JSAny signer_bytes,
    JSAny removals,
    JSAny aad,
    JSAny expected_previous_state,
    JSAny storage_entries,
    int storage_format_version,
  );

  external void wire__crate__api__group_e2ee__self_update_with_storage(
    NativePortType port_,
    JSAny group_id,
    JSAny signer_bytes,
    JSAny aad,
    JSAny expected_previous_state,
    JSAny expected_self_authority,
    JSAny storage_entries,
    int storage_format_version,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__keys__serialize_signer(
    int ciphersuite,
    JSAny private_key,
    JSAny public_key,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__types__supported_ciphersuites();

  external void wire__crate__api__group_e2ee__swap_members_with_storage(
    NativePortType port_,
    JSAny group_id,
    JSAny signer_bytes,
    JSAny removals,
    JSAny additions,
    JSAny aad,
    JSAny expected_previous_state,
    JSAny storage_entries,
    int storage_format_version,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsCredential(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMlsSignatureKeyPair(
    int ptr,
  );
}
