// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_native`, `native`

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MlsCredential>>
abstract class MlsCredential implements RustOpaqueInterface {
  /// Create a BasicCredential from identity bytes (e.g. user ID, email).
  static MlsCredential basic({required List<int> identity}) => RustLib
      .instance
      .api
      .crateApiCredentialMlsCredentialBasic(identity: identity);

  /// Returns the certificate chain from an X.509 credential.
  ///
  /// Each entry is a DER-encoded X.509 certificate.
  /// Returns an error if this is not an X.509 credential.
  List<Uint8List> certificates();

  /// Returns the credential type value (1 = Basic, 2 = X509).
  int credentialType();

  /// TLS-deserialize a credential from bytes.
  static MlsCredential deserialize({required List<int> bytes}) => RustLib
      .instance
      .api
      .crateApiCredentialMlsCredentialDeserialize(bytes: bytes);

  /// Returns the identity bytes from a BasicCredential.
  ///
  /// Returns an error if this is not a BasicCredential.
  Uint8List identity();

  /// TLS-serialize this credential for wire transmission.
  Uint8List serialize();

  /// Returns the raw serialized content of this credential.
  ///
  /// For BasicCredential, this is the identity bytes.
  /// For X.509, this is the TLS-serialized certificate chain.
  Uint8List serializedContent();

  /// Create an X.509 credential from a certificate chain.
  ///
  /// Each entry in `certificate_chain` is a DER-encoded X.509 certificate.
  /// The first certificate should be the end-entity (leaf) certificate,
  /// followed by intermediate certificates in order toward the root.
  ///
  /// # Security
  /// This function does **not** validate the certificate chain (expiration,
  /// signatures, revocation, or trust anchors). The application layer is
  /// responsible for verifying the X.509 chain before passing it here.
  static MlsCredential x509({required List<Uint8List> certificateChain}) =>
      RustLib.instance.api.crateApiCredentialMlsCredentialX509(
        certificateChain: certificateChain,
      );
}
