// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'config.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'storage.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `checked_u32`, `ensure_local_signer_public_key`, `ensure_local_signer`, `ensure_signer_public_key`, `group_state_digest_from_entries`, `hash_len_prefixed`, `join_group_from_welcome_with_storage_typed`, `leaf_matches_owner`, `prepare_membership_commit_with_storage`, `prepared_result`, `process_message_with_storage_typed`, `proposal_type`, `provider_with_base_digest`, `roster_digest`, `roster_from_group`, `selected_key_package_sha256`, `strict_receive_error`, `validate_additions`, `validate_canonical_leaves`, `validate_exact_delta`, `validate_expected_roster_typed`, `validate_expected_roster`, `validate_removals`, `validate_self_authority`, `zeroize_processed_content`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `StrictJoinGroupWithStorageResult`, `StrictReceiveErrorKind`, `StrictReceiveError`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Compute the canonical version-1 roster digest from caller-supplied fields.
Uint8List mlsRosterDigestV1({
  required List<int> groupId,
  required BigInt epoch,
  required List<MlsRosterLeafV1> leaves,
}) => RustLib.instance.api.crateApiGroupE2EeMlsRosterDigestV1(
  groupId: groupId,
  epoch: epoch,
  leaves: leaves,
);

/// Compute the local-only digest of the group rows in one caller snapshot.
///
/// Installation-global rows are validated but excluded. Rust's decoded copy
/// of each input value is zeroized before this function returns.
Uint8List mlsGroupStateDigest({
  required List<int> groupId,
  required List<MlsStorageEntry> storageEntries,
  required int storageFormatVersion,
}) => RustLib.instance.api.crateApiGroupE2EeMlsGroupStateDigest(
  groupId: groupId,
  storageEntries: storageEntries,
  storageFormatVersion: storageFormatVersion,
);

/// Create an owner-only group with an explicit server-issued group ID.
Future<CreateGroupWithStorageResult> createGroupWithStorage({
  required MlsGroupConfig config,
  required List<int> signerBytes,
  required List<int> explicitGroupId,
  required MlsAuthorizedOwnerV1 expectedOwnerAuthority,
  Uint8List? credentialBytes,
  required List<MlsStorageEntry> storageEntries,
  required int storageFormatVersion,
}) => RustLib.instance.api.crateApiGroupE2EeCreateGroupWithStorage(
  config: config,
  signerBytes: signerBytes,
  explicitGroupId: explicitGroupId,
  expectedOwnerAuthority: expectedOwnerAuthority,
  credentialBytes: credentialBytes,
  storageEntries: storageEntries,
  storageFormatVersion: storageFormatVersion,
);

/// Add exact authorized members and return deferred candidate state.
Future<PreparedCommitWithStorageResult> addMembersWithStorage({
  required List<int> groupId,
  required List<int> signerBytes,
  required List<MlsAuthorizedKeyPackageV1> additions,
  required List<int> aad,
  required MlsExpectedRosterStateV1 expectedPreviousState,
  required List<MlsStorageEntry> storageEntries,
  required int storageFormatVersion,
}) => RustLib.instance.api.crateApiGroupE2EeAddMembersWithStorage(
  groupId: groupId,
  signerBytes: signerBytes,
  additions: additions,
  aad: aad,
  expectedPreviousState: expectedPreviousState,
  storageEntries: storageEntries,
  storageFormatVersion: storageFormatVersion,
);

/// Remove exact authorized members and return deferred candidate state.
Future<PreparedCommitWithStorageResult> removeMembersWithStorage({
  required List<int> groupId,
  required List<int> signerBytes,
  required List<MlsAuthorizedRemovalV1> removals,
  required List<int> aad,
  required MlsExpectedRosterStateV1 expectedPreviousState,
  required List<MlsStorageEntry> storageEntries,
  required int storageFormatVersion,
}) => RustLib.instance.api.crateApiGroupE2EeRemoveMembersWithStorage(
  groupId: groupId,
  signerBytes: signerBytes,
  removals: removals,
  aad: aad,
  expectedPreviousState: expectedPreviousState,
  storageEntries: storageEntries,
  storageFormatVersion: storageFormatVersion,
);

/// Atomically replace members using one combined remove/add Commit.
Future<PreparedCommitWithStorageResult> swapMembersWithStorage({
  required List<int> groupId,
  required List<int> signerBytes,
  required List<MlsAuthorizedRemovalV1> removals,
  required List<MlsAuthorizedKeyPackageV1> additions,
  required List<int> aad,
  required MlsExpectedRosterStateV1 expectedPreviousState,
  required List<MlsStorageEntry> storageEntries,
  required int storageFormatVersion,
}) => RustLib.instance.api.crateApiGroupE2EeSwapMembersWithStorage(
  groupId: groupId,
  signerBytes: signerBytes,
  removals: removals,
  additions: additions,
  aad: aad,
  expectedPreviousState: expectedPreviousState,
  storageEntries: storageEntries,
  storageFormatVersion: storageFormatVersion,
);

/// Prepare a local self-update without changing installation identity or key.
Future<PreparedCommitWithStorageResult> selfUpdateWithStorage({
  required List<int> groupId,
  required List<int> signerBytes,
  required List<int> aad,
  required MlsExpectedRosterStateV1 expectedPreviousState,
  required MlsAuthorizedSelfV1 expectedSelfAuthority,
  required List<MlsStorageEntry> storageEntries,
  required int storageFormatVersion,
}) => RustLib.instance.api.crateApiGroupE2EeSelfUpdateWithStorage(
  groupId: groupId,
  signerBytes: signerBytes,
  aad: aad,
  expectedPreviousState: expectedPreviousState,
  expectedSelfAuthority: expectedSelfAuthority,
  storageEntries: storageEntries,
  storageFormatVersion: storageFormatVersion,
);

/// Join a Welcome only when its installed state matches canonical authority.
Future<JoinGroupWithStorageResult> joinGroupFromWelcomeWithStorage({
  required MlsGroupConfig config,
  required List<int> welcomeBytes,
  Uint8List? ratchetTreeBytes,
  required List<int> signerBytes,
  required MlsExpectedRosterStateV1 expectedResultingState,
  required List<MlsStorageEntry> storageEntries,
  required int storageFormatVersion,
}) => RustLib.instance.api.crateApiGroupE2EeJoinGroupFromWelcomeWithStorage(
  config: config,
  welcomeBytes: welcomeBytes,
  ratchetTreeBytes: ratchetTreeBytes,
  signerBytes: signerBytes,
  expectedResultingState: expectedResultingState,
  storageEntries: storageEntries,
  storageFormatVersion: storageFormatVersion,
);

/// Process a message only when both base and resulting roster authority match.
Future<ProcessMessageWithStorageResult> processMessageWithStorage({
  required List<int> groupId,
  required List<int> messageBytes,
  required List<int> expectedAad,
  required MlsExpectedRosterStateV1 expectedPreviousState,
  required MlsExpectedRosterStateV1 expectedResultingState,
  required List<MlsStorageEntry> storageEntries,
  required int storageFormatVersion,
}) => RustLib.instance.api.crateApiGroupE2EeProcessMessageWithStorage(
  groupId: groupId,
  messageBytes: messageBytes,
  expectedAad: expectedAad,
  expectedPreviousState: expectedPreviousState,
  expectedResultingState: expectedResultingState,
  storageEntries: storageEntries,
  storageFormatVersion: storageFormatVersion,
);

class CreateGroupWithStorageResult {
  final Uint8List groupId;
  final MlsRosterSummaryV1 resultingRoster;
  final MlsStorageBatch storageBatch;

  const CreateGroupWithStorageResult({
    required this.groupId,
    required this.resultingRoster,
    required this.storageBatch,
  });

  @override
  int get hashCode =>
      groupId.hashCode ^ resultingRoster.hashCode ^ storageBatch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateGroupWithStorageResult &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          resultingRoster == other.resultingRoster &&
          storageBatch == other.storageBatch;
}

class JoinGroupWithStorageResult {
  final Uint8List groupId;
  final MlsRosterSummaryV1 resultingRoster;
  final MlsStorageBatch storageBatch;

  const JoinGroupWithStorageResult({
    required this.groupId,
    required this.resultingRoster,
    required this.storageBatch,
  });

  @override
  int get hashCode =>
      groupId.hashCode ^ resultingRoster.hashCode ^ storageBatch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JoinGroupWithStorageResult &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          resultingRoster == other.resultingRoster &&
          storageBatch == other.storageBatch;
}

class MlsAuthorizedKeyPackageV1 {
  final Uint8List keyPackageBytes;
  final Uint8List expectedCredentialIdentity;
  final Uint8List expectedSignaturePublicKey;

  const MlsAuthorizedKeyPackageV1({
    required this.keyPackageBytes,
    required this.expectedCredentialIdentity,
    required this.expectedSignaturePublicKey,
  });

  @override
  int get hashCode =>
      keyPackageBytes.hashCode ^
      expectedCredentialIdentity.hashCode ^
      expectedSignaturePublicKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MlsAuthorizedKeyPackageV1 &&
          runtimeType == other.runtimeType &&
          keyPackageBytes == other.keyPackageBytes &&
          expectedCredentialIdentity == other.expectedCredentialIdentity &&
          expectedSignaturePublicKey == other.expectedSignaturePublicKey;
}

class MlsAuthorizedOwnerV1 {
  final Uint8List expectedCredentialIdentity;
  final Uint8List expectedSignaturePublicKey;

  const MlsAuthorizedOwnerV1({
    required this.expectedCredentialIdentity,
    required this.expectedSignaturePublicKey,
  });

  @override
  int get hashCode =>
      expectedCredentialIdentity.hashCode ^ expectedSignaturePublicKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MlsAuthorizedOwnerV1 &&
          runtimeType == other.runtimeType &&
          expectedCredentialIdentity == other.expectedCredentialIdentity &&
          expectedSignaturePublicKey == other.expectedSignaturePublicKey;
}

class MlsAuthorizedRemovalV1 {
  final int leafIndex;
  final Uint8List expectedCredentialIdentity;
  final Uint8List expectedSignaturePublicKey;

  const MlsAuthorizedRemovalV1({
    required this.leafIndex,
    required this.expectedCredentialIdentity,
    required this.expectedSignaturePublicKey,
  });

  @override
  int get hashCode =>
      leafIndex.hashCode ^
      expectedCredentialIdentity.hashCode ^
      expectedSignaturePublicKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MlsAuthorizedRemovalV1 &&
          runtimeType == other.runtimeType &&
          leafIndex == other.leafIndex &&
          expectedCredentialIdentity == other.expectedCredentialIdentity &&
          expectedSignaturePublicKey == other.expectedSignaturePublicKey;
}

class MlsAuthorizedSelfV1 {
  final int leafIndex;
  final Uint8List expectedCredentialIdentity;
  final Uint8List expectedSignaturePublicKey;

  const MlsAuthorizedSelfV1({
    required this.leafIndex,
    required this.expectedCredentialIdentity,
    required this.expectedSignaturePublicKey,
  });

  @override
  int get hashCode =>
      leafIndex.hashCode ^
      expectedCredentialIdentity.hashCode ^
      expectedSignaturePublicKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MlsAuthorizedSelfV1 &&
          runtimeType == other.runtimeType &&
          leafIndex == other.leafIndex &&
          expectedCredentialIdentity == other.expectedCredentialIdentity &&
          expectedSignaturePublicKey == other.expectedSignaturePublicKey;
}

class MlsExpectedRosterStateV1 {
  final Uint8List groupId;
  final BigInt epoch;
  final Uint8List digestSha256;

  const MlsExpectedRosterStateV1({
    required this.groupId,
    required this.epoch,
    required this.digestSha256,
  });

  @override
  int get hashCode => groupId.hashCode ^ epoch.hashCode ^ digestSha256.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MlsExpectedRosterStateV1 &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          epoch == other.epoch &&
          digestSha256 == other.digestSha256;
}

class MlsRosterLeafV1 {
  final int leafIndex;
  final Uint8List credentialIdentity;
  final Uint8List signaturePublicKey;

  const MlsRosterLeafV1({
    required this.leafIndex,
    required this.credentialIdentity,
    required this.signaturePublicKey,
  });

  @override
  int get hashCode =>
      leafIndex.hashCode ^
      credentialIdentity.hashCode ^
      signaturePublicKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MlsRosterLeafV1 &&
          runtimeType == other.runtimeType &&
          leafIndex == other.leafIndex &&
          credentialIdentity == other.credentialIdentity &&
          signaturePublicKey == other.signaturePublicKey;
}

class MlsRosterSummaryV1 {
  final Uint8List groupId;
  final BigInt epoch;
  final List<MlsRosterLeafV1> leaves;
  final Uint8List digestSha256;

  const MlsRosterSummaryV1({
    required this.groupId,
    required this.epoch,
    required this.leaves,
    required this.digestSha256,
  });

  @override
  int get hashCode =>
      groupId.hashCode ^
      epoch.hashCode ^
      leaves.hashCode ^
      digestSha256.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MlsRosterSummaryV1 &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          epoch == other.epoch &&
          leaves == other.leaves &&
          digestSha256 == other.digestSha256;
}

class PreparedCommitWithStorageResult {
  final Uint8List commit;
  final Uint8List? welcome;
  final Uint8List? groupInfo;
  final Uint8List commitSha256;
  final MlsRosterSummaryV1 previousRoster;
  final MlsRosterSummaryV1 resultingRoster;
  final Uint8List baseGroupStateSha256;
  final MlsStorageBatch storageBatch;

  const PreparedCommitWithStorageResult({
    required this.commit,
    this.welcome,
    this.groupInfo,
    required this.commitSha256,
    required this.previousRoster,
    required this.resultingRoster,
    required this.baseGroupStateSha256,
    required this.storageBatch,
  });

  @override
  int get hashCode =>
      commit.hashCode ^
      welcome.hashCode ^
      groupInfo.hashCode ^
      commitSha256.hashCode ^
      previousRoster.hashCode ^
      resultingRoster.hashCode ^
      baseGroupStateSha256.hashCode ^
      storageBatch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PreparedCommitWithStorageResult &&
          runtimeType == other.runtimeType &&
          commit == other.commit &&
          welcome == other.welcome &&
          groupInfo == other.groupInfo &&
          commitSha256 == other.commitSha256 &&
          previousRoster == other.previousRoster &&
          resultingRoster == other.resultingRoster &&
          baseGroupStateSha256 == other.baseGroupStateSha256 &&
          storageBatch == other.storageBatch;
}

class ProcessMessageWithStorageResult {
  final ProcessedMessageType messageType;
  final int? senderIndex;
  final BigInt previousEpoch;
  final BigInt resultingEpoch;
  final Uint8List? applicationMessage;
  final bool hasStagedCommit;
  final bool hasProposal;
  final MlsProposalType? proposalType;
  final MlsRosterSummaryV1 previousRoster;
  final MlsRosterSummaryV1 resultingRoster;
  final MlsStorageBatch storageBatch;

  const ProcessMessageWithStorageResult({
    required this.messageType,
    this.senderIndex,
    required this.previousEpoch,
    required this.resultingEpoch,
    this.applicationMessage,
    required this.hasStagedCommit,
    required this.hasProposal,
    this.proposalType,
    required this.previousRoster,
    required this.resultingRoster,
    required this.storageBatch,
  });

  @override
  int get hashCode =>
      messageType.hashCode ^
      senderIndex.hashCode ^
      previousEpoch.hashCode ^
      resultingEpoch.hashCode ^
      applicationMessage.hashCode ^
      hasStagedCommit.hashCode ^
      hasProposal.hashCode ^
      proposalType.hashCode ^
      previousRoster.hashCode ^
      resultingRoster.hashCode ^
      storageBatch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessMessageWithStorageResult &&
          runtimeType == other.runtimeType &&
          messageType == other.messageType &&
          senderIndex == other.senderIndex &&
          previousEpoch == other.previousEpoch &&
          resultingEpoch == other.resultingEpoch &&
          applicationMessage == other.applicationMessage &&
          hasStagedCommit == other.hasStagedCommit &&
          hasProposal == other.hasProposal &&
          proposalType == other.proposalType &&
          previousRoster == other.previousRoster &&
          resultingRoster == other.resultingRoster &&
          storageBatch == other.storageBatch;
}
