// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Initialize the openmls library.
///
/// This function is called from Dart during library initialization.
/// The library_path parameter is typically used for loading external
/// dependencies if needed.
void initOpenmls({required String libraryPath}) =>
    RustLib.instance.api.crateApiInitInitOpenmls(libraryPath: libraryPath);

/// Check if the openmls library is initialized.
///
/// Returns true if the library has been successfully initialized.
bool isOpenmlsInitialized() =>
    RustLib.instance.api.crateApiInitIsOpenmlsInitialized();
