// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `from_native`, `native`, `signer_from_bytes`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SerializableKeyPair`, `SerializableSigner`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`, `zeroize`

/// Serialize a `SignatureKeyPair` to JSON bytes including private key.
///
/// # Security
/// The returned bytes contain private key material.
Uint8List serializeSigner({
  required MlsCiphersuite ciphersuite,
  required List<int> privateKey,
  required List<int> publicKey,
}) => RustLib.instance.api.crateApiKeysSerializeSigner(
  ciphersuite: ciphersuite,
  privateKey: privateKey,
  publicKey: publicKey,
);

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MlsSignatureKeyPair>>
abstract class MlsSignatureKeyPair implements RustOpaqueInterface {
  /// Deserialize a key pair from bytes (public key + scheme only).
  ///
  /// Note: This only restores the public key and scheme. To reconstruct
  /// a full key pair with private key, use `from_raw()`.
  static MlsSignatureKeyPair deserializePublic({required List<int> bytes}) =>
      RustLib.instance.api.crateApiKeysMlsSignatureKeyPairDeserializePublic(
        bytes: bytes,
      );

  /// Reconstruct a key pair from raw private and public key bytes.
  ///
  /// # Security
  /// `private_key` is moved (not copied) into the key pair.
  static MlsSignatureKeyPair fromRaw({
    required MlsCiphersuite ciphersuite,
    required List<int> privateKey,
    required List<int> publicKey,
  }) => RustLib.instance.api.crateApiKeysMlsSignatureKeyPairFromRaw(
    ciphersuite: ciphersuite,
    privateKey: privateKey,
    publicKey: publicKey,
  );

  /// Generate a new signature key pair for the given ciphersuite's signature scheme.
  static MlsSignatureKeyPair generate({required MlsCiphersuite ciphersuite}) =>
      RustLib.instance.api.crateApiKeysMlsSignatureKeyPairGenerate(
        ciphersuite: ciphersuite,
      );

  /// Returns the private key bytes.
  ///
  /// # Security
  /// The returned bytes contain private key material. The caller is responsible
  /// for securely zeroing these bytes when done.
  Uint8List privateKey();

  /// Returns the public key bytes.
  Uint8List publicKey();

  /// Serialize the key pair to bytes for storage.
  ///
  /// The returned bytes contain the **public key and signature scheme only** —
  /// no private key material. To reconstruct a full key pair with private key,
  /// use `from_raw()` with the original private key bytes.
  Uint8List serialize();

  /// Returns the signature scheme as a u16.
  int signatureScheme();
}
