// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Extract the group ID from an MLS protocol message.
Uint8List mlsMessageExtractGroupId({required List<int> messageBytes}) => RustLib
    .instance
    .api
    .crateApiMessageMlsMessageExtractGroupId(messageBytes: messageBytes);

/// Extract the epoch from an MLS protocol message.
BigInt mlsMessageExtractEpoch({required List<int> messageBytes}) => RustLib
    .instance
    .api
    .crateApiMessageMlsMessageExtractEpoch(messageBytes: messageBytes);

/// Return `application`, `proposal`, or `commit` for a protocol message.
String mlsMessageContentType({required List<int> messageBytes}) => RustLib
    .instance
    .api
    .crateApiMessageMlsMessageContentType(messageBytes: messageBytes);
