// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `ciphersuite_to_native`, `wire_format_to_native`

/// Returns the list of supported ciphersuites.
List<MlsCiphersuite> supportedCiphersuites() =>
    RustLib.instance.api.crateApiTypesSupportedCiphersuites();

/// MLS ciphersuite selection.
enum MlsCiphersuite {
  mls128DhkemX25519Aes128GcmSha256Ed25519,
  mls128DhkemX25519Chacha20Poly1305Sha256Ed25519,
  mls128DhkemP256Aes128GcmSha256P256,
}

/// MLS proposal types.
enum MlsProposalType {
  add,
  remove,
  update,
  preSharedKey,
  reinit,
  externalInit,
  groupContextExtensions,
  custom,
}

/// Wire format policy for MLS messages.
enum MlsWireFormatPolicy { plaintext, ciphertext }

/// Type of a processed incoming message.
enum ProcessedMessageType { application, proposal, stagedCommit }
