// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `exact_uuid`, `private_authority`, `take_zeroizing`, `try_into_core`, `try_into_core`, `try_into_core`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AccountEnvelopeCrypto>>
abstract class AccountEnvelopeCrypto implements RustOpaqueInterface {
  static AccountEnvelopeSuccessorAuthorizationV1
  authorizeSuccessorPublicBundleV1({
    required AccountEnvelopePrivateBundleAuthorityInputV1
    expectedPreviousLocalPrivateBundleAuthority,
    required List<int> previousPrivateBundle,
    required List<int> selfSignedSuccessorPublicBundle,
  }) => RustLib.instance.api
      .crateApiAccountEnvelopeBridgeAccountEnvelopeCryptoAuthorizeSuccessorPublicBundleV1(
        expectedPreviousLocalPrivateBundleAuthority:
            expectedPreviousLocalPrivateBundleAuthority,
        previousPrivateBundle: previousPrivateBundle,
        selfSignedSuccessorPublicBundle: selfSignedSuccessorPublicBundle,
      );

  static AccountEnvelopePublicBundleCandidateV1 createSelfSignedPublicBundleV1({
    required List<int> accountId,
    required BigInt generation,
    required AccountEnvelopeActivationKindV1 activationKind,
    AccountEnvelopeResetReasonV1? resetReason,
    required BigInt previousGeneration,
    required AccountEnvelopePrivateBundleAuthorityInputV1
    expectedLocalPrivateBundleAuthority,
    required List<int> privateBundle,
  }) => RustLib.instance.api
      .crateApiAccountEnvelopeBridgeAccountEnvelopeCryptoCreateSelfSignedPublicBundleV1(
        accountId: accountId,
        generation: generation,
        activationKind: activationKind,
        resetReason: resetReason,
        previousGeneration: previousGeneration,
        expectedLocalPrivateBundleAuthority:
            expectedLocalPrivateBundleAuthority,
        privateBundle: privateBundle,
      );

  static GenerateAccountEnvelopeKeyBundleOutputV1 generateKeyBundleV1({
    required List<int> accountId,
    required BigInt generation,
    required List<int> rootInstallationId,
    required BigInt rootAuthorityGeneration,
  }) => RustLib.instance.api
      .crateApiAccountEnvelopeBridgeAccountEnvelopeCryptoGenerateKeyBundleV1(
        accountId: accountId,
        generation: generation,
        rootInstallationId: rootInstallationId,
        rootAuthorityGeneration: rootAuthorityGeneration,
      );

  static Uint8List sealContextInvitationPreviewV1({
    required ContextInvitationAuthorityInputV1 authority,
    required AccountEnvelopePrivateBundleAuthorityInputV1
    expectedLocalPrivateBundleAuthority,
    required ContextInvitationPreviewInputV1 preview,
    required List<int> recipientPublicBundle,
    required List<int> senderPrivateBundle,
  }) => RustLib.instance.api
      .crateApiAccountEnvelopeBridgeAccountEnvelopeCryptoSealContextInvitationPreviewV1(
        authority: authority,
        expectedLocalPrivateBundleAuthority:
            expectedLocalPrivateBundleAuthority,
        preview: preview,
        recipientPublicBundle: recipientPublicBundle,
        senderPrivateBundle: senderPrivateBundle,
      );

  static ContextInvitationPreviewOutputV1
  verifyAndOpenContextInvitationPreviewV1({
    required List<int> envelope,
    required ExpectedContextInvitationAuthorityInputV1 expectedAuthority,
    required List<int> recipientPrivateBundle,
    required List<int> senderPublicBundle,
  }) => RustLib.instance.api
      .crateApiAccountEnvelopeBridgeAccountEnvelopeCryptoVerifyAndOpenContextInvitationPreviewV1(
        envelope: envelope,
        expectedAuthority: expectedAuthority,
        recipientPrivateBundle: recipientPrivateBundle,
        senderPublicBundle: senderPublicBundle,
      );

  static VerifyAccountEnvelopeContinuityOutputV1 verifyContinuityResponseV1({
    Uint8List? pinnedPublicBundle,
    required List<Uint8List> continuityPublicBundles,
    required bool manualReanchorAuthorized,
  }) => RustLib.instance.api
      .crateApiAccountEnvelopeBridgeAccountEnvelopeCryptoVerifyContinuityResponseV1(
        pinnedPublicBundle: pinnedPublicBundle,
        continuityPublicBundles: continuityPublicBundles,
        manualReanchorAuthorized: manualReanchorAuthorized,
      );
}

/// Authenticated authority expected for one opaque private bundle.
class AccountEnvelopePrivateBundleAuthorityInputV1 {
  final Uint8List accountId;
  final BigInt generation;
  final Uint8List rootInstallationId;
  final BigInt rootAuthorityGeneration;

  const AccountEnvelopePrivateBundleAuthorityInputV1({
    required this.accountId,
    required this.generation,
    required this.rootInstallationId,
    required this.rootAuthorityGeneration,
  });

  @override
  int get hashCode =>
      accountId.hashCode ^
      generation.hashCode ^
      rootInstallationId.hashCode ^
      rootAuthorityGeneration.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountEnvelopePrivateBundleAuthorityInputV1 &&
          runtimeType == other.runtimeType &&
          accountId == other.accountId &&
          generation == other.generation &&
          rootInstallationId == other.rootInstallationId &&
          rootAuthorityGeneration == other.rootAuthorityGeneration;
}

/// Whether returned public bytes are publishable or await predecessor approval.
enum AccountEnvelopePublicBundleCandidateKindV1 {
  canonicalPublicBundle,
  nonPublishableRotationCandidate,
}

/// Self-signed public bundle bytes and their lifecycle classification.
class AccountEnvelopePublicBundleCandidateV1 {
  final AccountEnvelopePublicBundleCandidateKindV1 kind;
  final Uint8List bytes;

  const AccountEnvelopePublicBundleCandidateV1({
    required this.kind,
    required this.bytes,
  });

  @override
  int get hashCode => kind.hashCode ^ bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountEnvelopePublicBundleCandidateV1 &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          bytes == other.bytes;
}

/// Public, self-signature-verified canonical bundle fields.
class AccountEnvelopePublicBundleSummaryOutputV1 {
  final Uint8List accountId;
  final BigInt generation;
  final Uint8List hpkePublicKey;
  final Uint8List signaturePublicKey;
  final AccountEnvelopeActivationKindV1 activationKind;
  final BigInt previousGeneration;
  final AccountEnvelopeResetReasonV1? resetReason;
  final Uint8List digestSha256;

  const AccountEnvelopePublicBundleSummaryOutputV1({
    required this.accountId,
    required this.generation,
    required this.hpkePublicKey,
    required this.signaturePublicKey,
    required this.activationKind,
    required this.previousGeneration,
    this.resetReason,
    required this.digestSha256,
  });

  @override
  int get hashCode =>
      accountId.hashCode ^
      generation.hashCode ^
      hpkePublicKey.hashCode ^
      signaturePublicKey.hashCode ^
      activationKind.hashCode ^
      previousGeneration.hashCode ^
      resetReason.hashCode ^
      digestSha256.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountEnvelopePublicBundleSummaryOutputV1 &&
          runtimeType == other.runtimeType &&
          accountId == other.accountId &&
          generation == other.generation &&
          hpkePublicKey == other.hpkePublicKey &&
          signaturePublicKey == other.signaturePublicKey &&
          activationKind == other.activationKind &&
          previousGeneration == other.previousGeneration &&
          resetReason == other.resetReason &&
          digestSha256 == other.digestSha256;
}

/// Complete successor bytes and an inactive predecessor-retirement candidate.
class AccountEnvelopeSuccessorAuthorizationV1 {
  final Uint8List authorizedCanonicalSuccessorPublicBundle;
  final Uint8List retiredPreviousPrivateBundleCandidate;

  const AccountEnvelopeSuccessorAuthorizationV1({
    required this.authorizedCanonicalSuccessorPublicBundle,
    required this.retiredPreviousPrivateBundleCandidate,
  });

  @override
  int get hashCode =>
      authorizedCanonicalSuccessorPublicBundle.hashCode ^
      retiredPreviousPrivateBundleCandidate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountEnvelopeSuccessorAuthorizationV1 &&
          runtimeType == other.runtimeType &&
          authorizedCanonicalSuccessorPublicBundle ==
              other.authorizedCanonicalSuccessorPublicBundle &&
          retiredPreviousPrivateBundleCandidate ==
              other.retiredPreviousPrivateBundleCandidate;
}

/// Authenticated clear-header authority for a sealed invitation preview.
class ContextInvitationAuthorityInputV1 {
  final Uint8List envelopeId;
  final Uint8List inviteId;
  final Uint8List senderAccountId;
  final BigInt senderGeneration;
  final Uint8List recipientAccountId;
  final BigInt recipientGeneration;
  final BigInt authorityAttempt;
  final BigInt relaySlotVersion;
  final BigInt serverCreatedAtUnixMs;
  final BigInt serverExpiresAtUnixMs;
  final AccountEnvelopePaddingClassV1 paddingClass;

  const ContextInvitationAuthorityInputV1({
    required this.envelopeId,
    required this.inviteId,
    required this.senderAccountId,
    required this.senderGeneration,
    required this.recipientAccountId,
    required this.recipientGeneration,
    required this.authorityAttempt,
    required this.relaySlotVersion,
    required this.serverCreatedAtUnixMs,
    required this.serverExpiresAtUnixMs,
    required this.paddingClass,
  });

  @override
  int get hashCode =>
      envelopeId.hashCode ^
      inviteId.hashCode ^
      senderAccountId.hashCode ^
      senderGeneration.hashCode ^
      recipientAccountId.hashCode ^
      recipientGeneration.hashCode ^
      authorityAttempt.hashCode ^
      relaySlotVersion.hashCode ^
      serverCreatedAtUnixMs.hashCode ^
      serverExpiresAtUnixMs.hashCode ^
      paddingClass.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContextInvitationAuthorityInputV1 &&
          runtimeType == other.runtimeType &&
          envelopeId == other.envelopeId &&
          inviteId == other.inviteId &&
          senderAccountId == other.senderAccountId &&
          senderGeneration == other.senderGeneration &&
          recipientAccountId == other.recipientAccountId &&
          recipientGeneration == other.recipientGeneration &&
          authorityAttempt == other.authorityAttempt &&
          relaySlotVersion == other.relaySlotVersion &&
          serverCreatedAtUnixMs == other.serverCreatedAtUnixMs &&
          serverExpiresAtUnixMs == other.serverExpiresAtUnixMs &&
          paddingClass == other.paddingClass;
}

/// Caller-provided invitation preview. Rust normalizes and bounds every field.
class ContextInvitationPreviewInputV1 {
  final String? title;
  final List<String> tags;

  const ContextInvitationPreviewInputV1({this.title, required this.tags});

  @override
  int get hashCode => title.hashCode ^ tags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContextInvitationPreviewInputV1 &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          tags == other.tags;
}

/// Authenticated, normalized invitation preview returned after successful open.
class ContextInvitationPreviewOutputV1 {
  final String? title;
  final List<String> tags;

  const ContextInvitationPreviewOutputV1({this.title, required this.tags});

  @override
  int get hashCode => title.hashCode ^ tags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContextInvitationPreviewOutputV1 &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          tags == other.tags;
}

/// Authenticated open authority plus installation-local private-bundle binding.
class ExpectedContextInvitationAuthorityInputV1 {
  final ContextInvitationAuthorityInputV1 invitation;
  final Uint8List localRootInstallationId;
  final BigInt localRootAuthorityGeneration;

  const ExpectedContextInvitationAuthorityInputV1({
    required this.invitation,
    required this.localRootInstallationId,
    required this.localRootAuthorityGeneration,
  });

  @override
  int get hashCode =>
      invitation.hashCode ^
      localRootInstallationId.hashCode ^
      localRootAuthorityGeneration.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExpectedContextInvitationAuthorityInputV1 &&
          runtimeType == other.runtimeType &&
          invitation == other.invitation &&
          localRootInstallationId == other.localRootInstallationId &&
          localRootAuthorityGeneration == other.localRootAuthorityGeneration;
}

/// Opaque generated private bundle. Component keys are never exposed.
class GenerateAccountEnvelopeKeyBundleOutputV1 {
  final Uint8List privateBundle;

  const GenerateAccountEnvelopeKeyBundleOutputV1({required this.privateBundle});

  @override
  int get hashCode => privateBundle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GenerateAccountEnvelopeKeyBundleOutputV1 &&
          runtimeType == other.runtimeType &&
          privateBundle == other.privateBundle;
}

/// Verified continuity result. Reset anchors still require caller acceptance.
class VerifyAccountEnvelopeContinuityOutputV1 {
  final AccountEnvelopeContinuityDispositionV1 disposition;
  final Uint8List verifiedPublicBundle;
  final AccountEnvelopePublicBundleSummaryOutputV1 verifiedSummary;

  const VerifyAccountEnvelopeContinuityOutputV1({
    required this.disposition,
    required this.verifiedPublicBundle,
    required this.verifiedSummary,
  });

  @override
  int get hashCode =>
      disposition.hashCode ^
      verifiedPublicBundle.hashCode ^
      verifiedSummary.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VerifyAccountEnvelopeContinuityOutputV1 &&
          runtimeType == other.runtimeType &&
          disposition == other.disposition &&
          verifiedPublicBundle == other.verifiedPublicBundle &&
          verifiedSummary == other.verifiedSummary;
}
