// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `as_u8`, `authority_mismatch`, `ciphertext_bytes`, `from_u8`, `from_u8`, `from_u8`, `is_canonical_uuid`, `new`, `new`, `plaintext_bytes`, `validate`, `validate`, `validate`, `value`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AccountEnvelopeContinuityResponseV1`, `AccountEnvelopePrivateBundleAuthorityV1`, `AccountEnvelopePublicBundleSummaryV1`, `AuthorizeSuccessorPublicBundleResultV1`, `ContextInvitationAuthorityV1`, `ContextInvitationPreviewV1`, `DecodedPrivateBundleV1`, `ExpectedContextInvitationAuthorityV1`, `GenerateAccountEnvelopeKeyBundleResultV1`, `OpenContextInvitationPreviewResultV1`, `PrivateBundleStateV1`, `SealContextInvitationPreviewResultV1`, `SelfSignedPublicBundleResultV1`, `VerifyContinuityResponseResultV1`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `drop`, `drop`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

enum AccountEnvelopeActivationKindV1 { initial, rotation, continuityReset }

enum AccountEnvelopeContinuityDispositionV1 {
  firstObservation,
  pinnedUnchanged,
  rotationChainVerified,
  resetAnchorRequiresAcceptance,
  manualReanchorVerified,
}

enum AccountEnvelopeErrorCodeV1 {
  authorityMismatch,
  unsupportedVersion,
  nonCanonicalEncoding,
  signatureInvalid,
  hpkeOpenFailed,
  plaintextSchemaInvalid,
  boundsExceeded,
  privateBundleInvalid,
  internalCryptoFailure,
}

class AccountEnvelopeErrorV1 implements FrbException {
  final AccountEnvelopeErrorCodeV1 code;

  const AccountEnvelopeErrorV1({required this.code});

  @override
  int get hashCode => code.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountEnvelopeErrorV1 &&
          runtimeType == other.runtimeType &&
          code == other.code;
}

enum AccountEnvelopePaddingClassV1 { bytes512, bytes1024, bytes2048 }

enum AccountEnvelopeResetReasonV1 {
  identityReset,
  chatStoreReset,
  rootInstallationMove,
  rootOrDatabaseKeyLoss,
  accountRecovery,
  compromise,
}
